"""One Icarus driver, and one cycle model, for everything that simulates.

Three tools now generate a stimulus and put it through a gate level netlist:
stage 6's replay of a solver trace (`replay.py`), stage 7's extraction of the
output stream (`stage7_output.py`), and stage 7's gate (`verify_output.py`).
They have to agree about two things or their results cannot be compared with
each other -- how a cycle is laid out in time, and how the PDK's cell models are
put in front of Icarus -- so both live here rather than being written a second
time in each caller.

Stage 2's gate, `run.py`, is not one of them and is left alone: its testbenches
are written by hand, one per target, and they check a property rather than
sampling a bus. What it does own is `model_files`, which every caller here needs,
so the dependency runs that way round.

**The cycle model.** Inputs move while the clock is low, the design settles, the
outputs are sampled, and then the rising edge happens. So the sample taken at
cycle *t* is a function of the inputs at *t* and of the state left by *t* edges,
which is exactly what `stage6_invert.py`'s `S(t)` means and what
`docs/02-connectivity.md` says the VCD's zero delay dump already gives: an
output change is listed *before* the clock change at the same timestamp, so
sampling before the edge captures what the previous edge produced. Nothing here
re-derives that convention; it is written down once, in `SETTLE` and `EDGE` and
in the loop `clocked_bench` emits.

**The models.** Resolved by `run.model_files`, which lists them explicitly
rather than letting Icarus search: the per-strength wrappers include their base
model by bare name and the sequential models reach two directories up for UDP
primitives, so the files only compile where the library put them.

This is a library, not a tool: it takes no target and has no `main`. What it is
exercised by is `tools/verify_output.py`, which drives corpus circuits through
it and compares the result against a string declared before the run.
"""

import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from run import IMAGE, PDK, model_files                        # noqa: E402

# One rising edge per cycle. The inputs move while the clock is low, settle, and
# are sampled before the edge. The numbers are only a shape: the cell models run
# at unit delay, so nothing here is timing sensitive.
SETTLE, EDGE = 4, 1

# What `clocked_bench` prints for every cycle, and what `samples` reads back.
# A line rather than a VCD because the sample points are the interesting thing
# and they are already decided here -- a dump would have to be re-sampled at
# exactly these instants to say the same thing.
SAMPLE = re.compile(r"^SAMPLE\s+(\d+)\s+(.*)$", re.M)


def module_of(netlist):
    """The netlist's module name and port list, read from the netlist itself."""
    text = open(netlist, encoding="utf-8").read()
    head = re.search(r"^\s*module\s+(\w+)\s*\((.*?)\)\s*;", text, re.M | re.S)
    if not head:
        raise ValueError(f"{netlist}: cannot find a module declaration")
    ports = [p.strip().strip("\\").strip() for p in head.group(2).split(",")]
    return head.group(1), [p for p in ports if p]


def port_widths(netlist):
    """Every port's direction and width, as the netlist declares them.

    Yosys writes a bus as `output [7:0] O;` and a scalar with no range at all,
    so the range is what tells one from the other. Read here rather than
    assumed, because stage 7's whole job is finding a multi-bit output and a
    tool that assumed `O` was eight bits would be assuming the answer.
    """
    text = open(netlist, encoding="utf-8").read()
    found = {}
    pattern = re.compile(
        r"^\s*(input|output|inout)\s*(?:\[\s*(\d+)\s*:\s*(\d+)\s*\])?\s*"
        r"\\?([\w$]+)\s*;", re.M)
    for direction, high, low, name in pattern.findall(text):
        width = 1 if high == "" else abs(int(high) - int(low)) + 1
        found[name] = {"direction": direction, "width": width}
    return found


def clocked_bench(top, module_ports, clocks, widths, rows, watch, notes=None):
    """A testbench that drives one row per cycle and prints one sample per cycle.

    `rows` is a list of dicts, one per cycle, mapping input port to an integer.
    `watch` maps an output port to its width. `notes` optionally maps a cycle
    number to a string printed beside that cycle's sample, which is how stage 7
    marks where a solver trace ends and its extension begins.
    """
    notes = notes or {}
    inputs = sorted(widths)
    outputs = sorted(watch)
    lines = [
        "// Generated by tools/sim/harness.py.",
        "// One rising edge per cycle; inputs applied while the clock is low",
        "// and outputs sampled before the edge, which is the cycle model",
        "// tools/stage6_invert.py unrolls.",
        "",
        "`timescale 1ns / 1ps",
        "",
        "module tb_harness;",
    ]
    for clock in clocks:
        lines.append(f"  reg {clock} = 1'b0;")
    for name in inputs:
        lines.append(f"  reg [{widths[name] - 1}:0] {name};")
    for name in outputs:
        lines.append(f"  wire [{watch[name] - 1}:0] {name};")
    lines.append("")
    connections = ", ".join(f".{p}({p})" for p in sorted(module_ports))
    lines.append(f"  {top} dut ({connections});")
    lines.append("")
    lines.append("  initial begin")

    shown = " ".join(f"{p}=%b" for p in outputs)
    arguments = ", ".join(outputs)
    for cycle, row in enumerate(rows):
        for name in inputs:
            lines.append(f"    {name} = {widths[name]}'d{row[name]};")
        lines.append(f"    #{SETTLE};")
        note = f"   {notes[cycle]}" if cycle in notes else ""
        lines.append(f'    $display("SAMPLE %0d {shown}{note}", '
                     f"{cycle}, {arguments});")
        for clock in clocks:
            lines.append(f"    #{EDGE} {clock} = 1'b1;")
        lines.append(f"    #{SETTLE};")
        for clock in clocks:
            lines.append(f"    #{EDGE} {clock} = 1'b0;")
    lines += ['    $display("CYCLES %0d", ' + str(len(rows)) + ");",
              "    $finish;",
              "  end",
              "",
              "endmodule"]
    return "\n".join(lines) + "\n"


def samples(output):
    """The per cycle sample lines, back out of a run's stdout.

    Each value stays a bit string rather than becoming an integer, because `x`
    and `z` are answers a gate level simulation gives and turning them into a
    number would be inventing one. `value()` below is where a caller decides
    what to do about that.
    """
    rows = []
    for cycle, rest in SAMPLE.findall(output):
        record = {"cycle": int(cycle), "note": ""}
        for field in rest.split():
            if "=" in field:
                name, bits = field.split("=", 1)
                record[name] = bits
            else:
                record["note"] = (record["note"] + " " + field).strip()
        rows.append(record)
    return rows


def value(bits):
    """A sampled bit string as an integer, or None if it carries x or z."""
    return int(bits, 2) if bits and set(bits) <= {"0", "1"} else None


def icarus(netlist, bench_path, extra_sources=(), image=IMAGE):
    """Compile and run one testbench against one netlist, in the container.

    Returns (returncode, combined output, cells, models). A missing cell model
    comes back as code 2 with an empty model list and the names in the output,
    rather than as an exception: the caller has a better sentence to say about
    it than a traceback does.

    FUNCTIONAL selects the plain logic models over the behavioural ones, which
    carry specify blocks and hold `x` without a timing annotated run;
    UNIT_DELAY is the delay macro those models expect. Without both, every cell
    output stays `x` and a correct netlist looks broken.
    """
    if not os.path.isdir(PDK):
        raise FileNotFoundError(f"{PDK} missing, run tools/fetch_pdk.py first")
    cells, files, includes, missing = model_files(netlist)
    if missing:
        return (2, "no model in the PDK cache for: " + ", ".join(missing),
                cells, [])
    sources = [bench_path.replace("\\", "/"), netlist.replace("\\", "/")]
    sources += [s.replace("\\", "/") for s in extra_sources]
    build = ("iverilog -g2012 -DFUNCTIONAL -DUNIT_DELAY=#1 -o /tmp/sim.vvp "
             + " ".join(f"-I {d}" for d in includes) + " "
             + " ".join(sources + files))
    done = subprocess.run(
        ["docker", "run", "--rm", "-v", f"{os.path.abspath('.')}:/work",
         "-w", "/work", image, "bash", "-c",
         f"set -e; {build}; vvp /tmp/sim.vvp"],
        capture_output=True, text=True)
    return done.returncode, done.stdout + done.stderr, cells, files
