"""Stage 6's trace, replayed through stage 2's netlist. The gate on the answer.

`docs/solver-pipeline.md`: *cross check any solver result by feeding the
recovered input sequence back through the stage 2 simulation. A trace that does
not reproduce in simulation indicates a modelling error in the export, not a
solution.*

This is that check, and it is the only thing standing between a wrong entry in
`graph.json`'s `cell_functions` and a wrong final answer. Nothing else would
notice: stage 6 reads those functions to build its transition relation, so a
corrupted one produces a self-consistent trace for a design that does not exist.
Simulation reads the PDK's own Verilog models instead, which is a different file
by a different author, and the two only agree if the model is right.

It is deliberately run against `out/<target>/netlist.v` -- **stage 2's** netlist,
not stage 3's `graph.v`. Stage 6 solves the graph; stage 2 simulates the
extraction. Replaying the graph's own trace against the graph would check the
solver and nothing else.

**The cycle model, matched to `stage6_invert.py`.** Inputs are applied while the
clock is low, the outputs are sampled after they settle and before the rising
edge, and then the edge happens. So cycle t's output is a function of the inputs
at t and the state after t edges, which is what the solver's `S(t)` means.

**What is asserted, and what is only reported.** The gate is the property: the
named output must be exactly 1 at the predicted cycle. The other cycles are
printed beside the model's prediction and not asserted, because simulation
starts every flop at `x` and the solver started from a definite state it chose.
Where the two agree, that is worth seeing; where simulation still holds `x`, the
trace has not yet flushed the design's state. The property cycle can be asserted
because `stage6_invert.py` proves the trace drives the output high from *every*
starting state before it writes it down.

Usage:
    python tools/sim/replay.py warmup
    python tools/sim/replay.py warmup --solution out/warmup/tampered.json
    python tools/sim/replay.py --dir out/synth/streamer_hello   # a corpus
                                                                # circuit,
                                                                # not a
                                                                # named
                                                                # target
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from run import PDK                                            # noqa: E402
# The cycle model and the Icarus invocation live in one place, because stage 7
# extracts its byte stream from the same simulation and a second driver would be
# a second set of conventions to keep in step. `replay.py` still writes its own
# testbench: it asserts a property and prints the solver's prediction beside
# every cycle, which is a different job from sampling a bus.
from harness import (SETTLE, EDGE, icarus, module_of,          # noqa: E402
                     port_widths)

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from stage1_cells import TARGETS                               # noqa: E402


def testbench(solution, top, module_ports, out_widths):
    """A testbench for exactly this trace, generated from the solution.

    `out_widths` comes from the netlist rather than from the solution, because
    the solution packs a bus into one integer and says nothing about how wide it
    was. Declared as a scalar, an eight bit output connects only its bit 0 and
    the other seven float: the warm up has one 1-bit output and never showed it,
    and the puzzle's `O[7:0]` would have.
    """
    inputs = sorted(solution["widths"])
    widths = solution["widths"]
    clocks = solution["clock_ports"]
    port = solution["property"]["port"]
    at = solution["property"]["cycle"]
    outputs = sorted(solution["predicted_outputs"][0])

    lines = [
        "// Generated by tools/sim/replay.py from a stage 6 solution.",
        "// One rising edge per cycle; inputs applied while the clock is low",
        "// and outputs sampled before the edge, which is the cycle model",
        "// tools/stage6_invert.py unrolls.",
        "",
        "`timescale 1ns / 1ps",
        "",
        "module tb_solution;",
    ]
    for clock in clocks:
        lines.append(f"  reg {clock} = 1'b0;")
    for name in inputs:
        lines.append(f"  reg [{widths[name] - 1}:0] {name};")
    for name in outputs:
        width = out_widths.get(name, 1)
        lines.append(f"  wire {name};" if width == 1
                     else f"  wire [{width - 1}:0] {name};")
    lines.append("  integer mismatches = 0;")
    lines.append("  integer unknown = 0;")
    lines.append("")

    connections = ", ".join(f".{p}({p})" for p in sorted(module_ports))
    lines.append(f"  {top} dut ({connections});")
    lines.append("")
    lines.append("  initial begin")

    for cycle, row in enumerate(solution["trace"]):
        predicted = solution["predicted_outputs"][cycle]
        lines.append(f"    // cycle {cycle}")
        for name in inputs:
            lines.append(f"    {name} = {widths[name]}'d{row[name]};")
        lines.append(f"    #{SETTLE};")
        shown = " ".join(f"{p}=%b" for p in outputs)
        arguments = ", ".join(outputs)
        lines.append(f'    $display("cycle %0d   {shown}   model says '
                     f'{" ".join(f"{p}={predicted[p]}" for p in outputs)}", '
                     f'{cycle}, {arguments});')
        if cycle == at:
            lines.append(f"    if ({port} === 1'b1)")
            lines.append(f'      $display("  the property holds: {port} is 1 '
                         f'at cycle %0d", {cycle});')
            lines.append(f"    else if ({port} === 1'bx)")
            lines.append("      begin unknown = unknown + 1;")
            lines.append(f'        $display("  {port} is x at cycle %0d: the '
                         f'trace does not flush this design\'s state", '
                         f'{cycle}); end')
            lines.append("    else")
            lines.append("      begin mismatches = mismatches + 1;")
            lines.append(f'        $display("  {port} is %b at cycle %0d and '
                         f'the model said 1", {port}, {cycle}); end')
        for clock in clocks:
            lines.append(f"    #{EDGE} {clock} = 1'b1;")
        lines.append(f"    #{SETTLE};")
        for clock in clocks:
            lines.append(f"    #{EDGE} {clock} = 1'b0;")
        lines.append("")

    lines += [
        '    $display("");',
        f'    $display("cycles replayed  {len(solution["trace"])}");',
        f'    $display("property        {port} high at cycle {at}");',
        '    $display("mismatches      %0d", mismatches);',
        '    $display("unknown         %0d", unknown);',
        "    if (mismatches == 0 && unknown == 0)",
        '      $display("RESULT: pass");',
        "    else",
        '      $display("RESULT: FAIL");',
        "    $finish;",
        "  end",
        "",
        "endmodule",
    ]
    return "\n".join(lines) + "\n"


def counted(output, label):
    """A count the testbench printed, or -1 if it did not print one.

    The bench writes `mismatches      0` and `unknown         1`. Reading them
    back is how the caller tells a disagreement from an unresolved `x`, which
    are different findings and had been sharing a verdict.
    """
    match = re.search(rf"(?m)^{label}\s+(\d+)\s*$", output)
    return int(match.group(1)) if match else -1


def run(target, solution_path=None, art_dir=None):
    # `art_dir` is where this target's artifacts live. It defaults to the
    # layout every named target uses, and is given explicitly for a corpus
    # circuit, whose netlist sits under out/synth/<name>/ and which is not in
    # TARGETS. Mirrors `--graph` in stage6_invert.py: the gate is the same, only
    # the path is supplied rather than derived.
    art_dir = art_dir or os.path.join("out", target)
    solution_path = solution_path or os.path.join(art_dir, "solution.json")
    if not os.path.exists(solution_path):
        sys.exit(f"{solution_path} missing; run tools/stage6_invert.py {target}")
    with open(solution_path, encoding="utf-8") as handle:
        solution = json.load(handle)

    # Stage 2's netlist, on purpose: stage 6 solved stage 3's graph, and a
    # cross check has to come from the other representation. For a corpus
    # circuit the same relation holds one step earlier: stage 5 synthesised
    # netlist.v and stage 3 read graph.json out of it.
    netlist = os.path.join(art_dir, "netlist.v")
    if not os.path.exists(netlist):
        sys.exit(f"{netlist} missing; run tools/stage2_nets.py {target}")
    if not os.path.isdir(PDK):
        sys.exit(f"{PDK} missing, run tools/fetch_pdk.py first")

    top, ports = module_of(netlist)
    declared_widths = port_widths(netlist)
    port = solution["property"]["port"]
    at = solution["property"]["cycle"]
    print(f"target {target}")
    print(f"  solution   {solution_path.replace(os.sep, '/')}   "
          f"depth {solution['depth']}, {len(solution['trace'])} cycles")
    print(f"  gate       {port} is 1 at cycle {at}, in simulation, against "
          f"stage 2's netlist")
    print(f"  under test {netlist.replace(os.sep, '/')}   module {top}")
    if not solution.get("initial_state_independent"):
        print(f"  NOTE: this trace was not proven independent of the starting "
              f"state, so\n        simulation from x may legitimately "
              f"disagree with it.")

    declared = set(solution["widths"]) | set(solution["clock_ports"]) \
        | set(solution["predicted_outputs"][0])
    if declared != set(ports):
        print(f"  solution ports {sorted(declared)}")
        print(f"  netlist ports  {sorted(ports)}")
        print("\nRESULT: fail, the trace and the netlist are not about the "
              "same design")
        return 2

    out_dir = art_dir
    bench = os.path.join(out_dir, "tb_solution.v").replace("\\", "/")
    with open(bench, "w", encoding="utf-8") as handle:
        handle.write(testbench(
            solution, top, ports,
            {n: w["width"] for n, w in declared_widths.items()}))
    print(f"  testbench  {bench}, generated for this trace")

    code, output, cells, files = icarus(netlist, bench)
    if code == 2 and not files:
        print(output)
        return 2
    print(f"  {len(cells)} cell types, {len(files)} models\n")
    print(output.strip())

    if code != 0:
        print("\nRESULT: simulation did not run")
        return 2
    if "RESULT: pass" in output:
        print(f"\nRESULT: pass, the trace reproduces and {port} is high at "
              f"cycle {at}")
        return 0

    # Two different things reached this line and were given one verdict. A
    # cycle that disagrees is a modelling defect. A cycle that is still `x`
    # under a trace whose own solution says it was never proven independent of
    # the starting state is the weaker claim behaving exactly as the NOTE above
    # says it may -- and calling that "a defect in the model" contradicts the
    # note printed twenty lines earlier, in the same run. This is problem 49's
    # shape: one cell for two states, where the third is neither pass nor fail.
    mismatches = counted(output, "mismatches")
    unknown = counted(output, "unknown")
    if (mismatches == 0 and unknown > 0
            and not solution.get("initial_state_independent")):
        print(f"\nRESULT: unconfirmable, {port} is x at cycle {at} and no "
              f"cycle disagrees.\nThe trace was proven only over this mode's "
              f"start states, and simulation\nbegins at x, so this is "
              f"consistent with the claim that was made. It is not\nevidence "
              f"for it. Re-run stage 6 without --post-reset for a trace that "
              f"can be\nconfirmed from x, which is the stronger claim anyway.")
        return 3
    print(f"\nRESULT: fail, the trace does not reproduce. That is a defect in "
          f"the\nmodel tools/stage6_invert.py built, not a solution.")
    return 1


if __name__ == "__main__":
    args = sys.argv[1:]
    override, art_dir, rest, index = None, None, [], 0
    while index < len(args):
        if args[index] == "--solution":
            override, index = args[index + 1], index + 2
        elif args[index] == "--dir":
            art_dir, index = args[index + 1], index + 2
        else:
            rest.append(args[index])
            index += 1
    if art_dir is not None:
        target = rest[0] if rest else os.path.basename(
            art_dir.rstrip("/\\")) or art_dir
    else:
        if len(rest) != 1 or rest[0] not in TARGETS:
            sys.exit(f"usage: python tools/sim/replay.py "
                     f"[{' | '.join(TARGETS)}] [--solution <path>]\n"
                     f"       python tools/sim/replay.py --dir "
                     f"out/synth/<circuit> [--solution <path>]")
        target = rest[0]
    sys.exit(run(target, override, art_dir))
