"""Stage 6's trace, replayed through stage 2's netlist. The gate on the answer.

`docs/solver-pipeline.md`: *cross check any solver result by feeding the
recovered input sequence back through the stage 2 simulation. A trace that does
not reproduce in simulation indicates a modelling error in the export, not a
solution.*

This is that check, and it is the only thing standing between a wrong entry in
`graph.json`'s `cell_functions` and a wrong final answer. Nothing else would
notice: stage 6 reads those functions to build its transition relation, so a
corrupted one produces a self-consistent trace for a design that does not exist.
Simulation reads the PDK's own Verilog models instead, which is a different file
by a different author, and the two only agree if the model is right.

It is deliberately run against `out/<target>/netlist.v` -- **stage 2's** netlist,
not stage 3's `graph.v`. Stage 6 solves the graph; stage 2 simulates the
extraction. Replaying the graph's own trace against the graph would check the
solver and nothing else.

**The cycle model, matched to `stage6_invert.py`.** Inputs are applied while the
clock is low, the outputs are sampled after they settle and before the rising
edge, and then the edge happens. So cycle t's output is a function of the inputs
at t and the state after t edges, which is what the solver's `S(t)` means.

**What is asserted, and what is only reported.** The gate is the property: the
named output must be exactly 1 at the predicted cycle. The other cycles are
printed beside the model's prediction and not asserted, because simulation
starts every flop at `x` and the solver started from a definite state it chose.
Where the two agree, that is worth seeing; where simulation still holds `x`, the
trace has not yet flushed the design's state. The property cycle can be asserted
because `stage6_invert.py` proves the trace drives the output high from *every*
starting state before it writes it down.

Usage:
    python tools/sim/replay.py warmup
    python tools/sim/replay.py warmup --solution out/warmup/tampered.json
"""

import json
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from run import IMAGE, PDK, model_files                        # noqa: E402

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from stage1_cells import TARGETS                               # noqa: E402

# One rising edge per cycle. The inputs move while the clock is low, settle,
# and are sampled before the edge; the numbers are only a shape and nothing
# here is timing sensitive, because the cell models run at unit delay.
SETTLE, EDGE = 4, 1


def testbench(solution, top, module_ports):
    """A testbench for exactly this trace, generated from the solution."""
    inputs = sorted(solution["widths"])
    widths = solution["widths"]
    clocks = solution["clock_ports"]
    port = solution["property"]["port"]
    at = solution["property"]["cycle"]
    outputs = sorted(solution["predicted_outputs"][0])

    lines = [
        "// Generated by tools/sim/replay.py from a stage 6 solution.",
        "// One rising edge per cycle; inputs applied while the clock is low",
        "// and outputs sampled before the edge, which is the cycle model",
        "// tools/stage6_invert.py unrolls.",
        "",
        "`timescale 1ns / 1ps",
        "",
        "module tb_solution;",
    ]
    for clock in clocks:
        lines.append(f"  reg {clock} = 1'b0;")
    for name in inputs:
        lines.append(f"  reg [{widths[name] - 1}:0] {name};")
    for name in outputs:
        lines.append(f"  wire {name};")
    lines.append("  integer mismatches = 0;")
    lines.append("  integer unknown = 0;")
    lines.append("")

    connections = ", ".join(f".{p}({p})" for p in sorted(module_ports))
    lines.append(f"  {top} dut ({connections});")
    lines.append("")
    lines.append("  initial begin")

    for cycle, row in enumerate(solution["trace"]):
        predicted = solution["predicted_outputs"][cycle]
        lines.append(f"    // cycle {cycle}")
        for name in inputs:
            lines.append(f"    {name} = {widths[name]}'d{row[name]};")
        lines.append(f"    #{SETTLE};")
        shown = " ".join(f"{p}=%b" for p in outputs)
        arguments = ", ".join(outputs)
        lines.append(f'    $display("cycle %0d   {shown}   model says '
                     f'{" ".join(f"{p}={predicted[p]}" for p in outputs)}", '
                     f'{cycle}, {arguments});')
        if cycle == at:
            lines.append(f"    if ({port} === 1'b1)")
            lines.append(f'      $display("  the property holds: {port} is 1 '
                         f'at cycle %0d", {cycle});')
            lines.append(f"    else if ({port} === 1'bx)")
            lines.append("      begin unknown = unknown + 1;")
            lines.append(f'        $display("  {port} is x at cycle %0d: the '
                         f'trace does not flush this design\'s state", '
                         f'{cycle}); end')
            lines.append("    else")
            lines.append("      begin mismatches = mismatches + 1;")
            lines.append(f'        $display("  {port} is %b at cycle %0d and '
                         f'the model said 1", {port}, {cycle}); end')
        for clock in clocks:
            lines.append(f"    #{EDGE} {clock} = 1'b1;")
        lines.append(f"    #{SETTLE};")
        for clock in clocks:
            lines.append(f"    #{EDGE} {clock} = 1'b0;")
        lines.append("")

    lines += [
        '    $display("");',
        f'    $display("cycles replayed  {len(solution["trace"])}");',
        f'    $display("property        {port} high at cycle {at}");',
        '    $display("mismatches      %0d", mismatches);',
        '    $display("unknown         %0d", unknown);',
        "    if (mismatches == 0 && unknown == 0)",
        '      $display("RESULT: pass");',
        "    else",
        '      $display("RESULT: FAIL");',
        "    $finish;",
        "  end",
        "",
        "endmodule",
    ]
    return "\n".join(lines) + "\n"


def module_of(netlist):
    """The netlist's module name and port list, read from the netlist itself."""
    import re
    text = open(netlist, encoding="utf-8").read()
    head = re.search(r"^\s*module\s+(\w+)\s*\((.*?)\)\s*;", text, re.M | re.S)
    if not head:
        sys.exit(f"{netlist}: cannot find a module declaration")
    ports = [p.strip().strip("\\").strip() for p in head.group(2).split(",")]
    return head.group(1), [p for p in ports if p]


def run(target, solution_path=None):
    solution_path = solution_path or os.path.join("out", target, "solution.json")
    if not os.path.exists(solution_path):
        sys.exit(f"{solution_path} missing; run tools/stage6_invert.py {target}")
    with open(solution_path, encoding="utf-8") as handle:
        solution = json.load(handle)

    # Stage 2's netlist, on purpose: stage 6 solved stage 3's graph, and a
    # cross check has to come from the other representation.
    netlist = os.path.join("out", target, "netlist.v")
    if not os.path.exists(netlist):
        sys.exit(f"{netlist} missing; run tools/stage2_nets.py {target}")
    if not os.path.isdir(PDK):
        sys.exit(f"{PDK} missing, run tools/fetch_pdk.py first")

    top, ports = module_of(netlist)
    port = solution["property"]["port"]
    at = solution["property"]["cycle"]
    print(f"target {target}")
    print(f"  solution   {solution_path.replace(os.sep, '/')}   "
          f"depth {solution['depth']}, {len(solution['trace'])} cycles")
    print(f"  gate       {port} is 1 at cycle {at}, in simulation, against "
          f"stage 2's netlist")
    print(f"  under test {netlist.replace(os.sep, '/')}   module {top}")
    if not solution.get("initial_state_independent"):
        print(f"  NOTE: this trace was not proven independent of the starting "
              f"state, so\n        simulation from x may legitimately "
              f"disagree with it.")

    declared = set(solution["widths"]) | set(solution["clock_ports"]) \
        | set(solution["predicted_outputs"][0])
    if declared != set(ports):
        print(f"  solution ports {sorted(declared)}")
        print(f"  netlist ports  {sorted(ports)}")
        print("\nRESULT: fail, the trace and the netlist are not about the "
              "same design")
        return 2

    out_dir = os.path.join("out", target)
    bench = os.path.join(out_dir, "tb_solution.v").replace("\\", "/")
    with open(bench, "w", encoding="utf-8") as handle:
        handle.write(testbench(solution, top, ports))
    print(f"  testbench  {bench}, generated for this trace")

    cells, files, includes, missing = model_files(netlist)
    if missing:
        print(f"no model in the PDK cache for: {missing}")
        return 2
    print(f"  {len(cells)} cell types, {len(files)} models\n")

    build = ("iverilog -g2012 -DFUNCTIONAL -DUNIT_DELAY=#1 -o /tmp/sim.vvp "
             + " ".join(f"-I {d}" for d in includes) + " "
             + f"{bench} {netlist.replace(chr(92), '/')} " + " ".join(files))
    result = subprocess.run(
        ["docker", "run", "--rm", "-v", f"{os.path.abspath('.')}:/work",
         "-w", "/work", IMAGE, "bash", "-c", f"set -e; {build}; vvp /tmp/sim.vvp"],
        capture_output=True, text=True)
    output = result.stdout + result.stderr
    print(output.strip())

    if result.returncode != 0:
        print("\nRESULT: simulation did not run")
        return 2
    if "RESULT: pass" in output:
        print(f"\nRESULT: pass, the trace reproduces and {port} is high at "
              f"cycle {at}")
        return 0
    print(f"\nRESULT: fail, the trace does not reproduce. That is a defect in "
          f"the\nmodel tools/stage6_invert.py built, not a solution.")
    return 1


if __name__ == "__main__":
    args = sys.argv[1:]
    override = None
    if len(args) >= 3 and args[1] == "--solution":
        override, args = args[2], args[:1]
    if len(args) != 1 or args[0] not in TARGETS:
        sys.exit(f"usage: python tools/sim/replay.py "
                 f"[{' | '.join(TARGETS)}] [--solution <path>]")
    sys.exit(run(args[0], override))
