"""Easter-egg sweep, domain A1+A2: GDS text/label records and structure names.

For each GDS target this tool reports, deterministically:

  1. Header facts read straight from the binary records (not through gdstk):
     library name, GDS version, units, and the BGNLIB / per-structure BGNSTR
     timestamps rendered as dates.
  2. Every structure (cell) name with its reference count, partitioned into
     known PDK cells (sky130_fd_sc_hd__*), known non-cells (VIA_*, INTERNAL_*,
     the top cell), and ANYTHING ELSE, which is always printed in full.
  3. Every Label/text record: text, (layer, texttype), position, owning
     structure. Expected pin labels live on li1 (67,5) and met1 (68,5) and
     look like port/net identifiers; anything on another layer, or any text
     that reads like a word/message rather than an identifier, is flagged.

The label walk reuses the approach of tools/gds_survey.py (iterate
library.cells, then cell.labels) without modifying that tool.

Usage:
    .venv-linux/bin/python tools/egg_labels.py puzzle warmup
    .venv-linux/bin/python tools/egg_labels.py path/to/file.gds
    .venv-linux/bin/python tools/egg_labels.py --selftest

--selftest builds an in-memory gdstk library holding one innocuous pin-like
label on (67,5) and one planted message label on an odd layer; the classifier
must flag exactly the planted one, or the tool exits non-zero.

The full structured inventory for each target is written to
out/eggs/labels_<target>.json.
"""

import json
import re
import struct
import sys
from collections import Counter
from pathlib import Path

import gdstk

REPO = Path(__file__).resolve().parent.parent

TARGETS = {
    "puzzle": REPO / "puzzle" / "puzzle.gds",
    "warmup": REPO / "puzzle" / "warmup" / "04_final.gds",
}

# The two (layer, texttype) pairs where this PDK's pin labels are expected:
# li1 (67,5) and met1 (68,5). Recorded in CLAUDE.md and docs/00-environment.md.
PIN_LABEL_LAYERS = {(67, 5), (68, 5)}

# A port/net-like name: an identifier, optionally a single bus index. Covers
# clk, rst_n, enable, I, success, O[7], n42, VGND, VPWR. Anything with a
# space, punctuation, or other structure fails this and reads as a message.
IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_.$]*(\[[0-9]+\])?\Z")

# --- The mundane tier -------------------------------------------------------
# A flagged label is still mundane if it is standard sky130 / OpenLane output.
# These rules are the *control* for the flag: anything they do not explain is
# reported as unexplained and is the only candidate-egg output of this tool.

# Power and well pins that every sky130_fd_sc_hd cell carries as labels.
POWER_NAMES = {"VPWR", "VGND", "VPB", "VNB"}

# Documented ports of the two targets (puzzle/README.md, warmup/00_source.v)
# plus their power nets. A top-cell label with one of these texts is a port
# label wherever the router chose to put it (met2..met5 for top-level pins).
KNOWN_PORTS = {
    "clk", "rst_n", "enable", "I", "success",
    "en", "A", "B", "S",
} | POWER_NAMES
KNOWN_PORT_BUS = re.compile(r"O\[[0-7]\]\Z")

# Autogenerated net names from synthesis/P&R.
NET_NAME = re.compile(r"(n|net|_)\d+_?\Z")

# A cell pin name inside a library cell: short, upper-case identifier
# (A, B1, X, Y, D, Q, CLK, RESET_B, SET_B, GATE, A_N, ...).
CELL_PIN = re.compile(r"[A-Z][A-Z0-9_]{0,11}\Z")

# Label layers the sky130 PDK and OpenLane legitimately write text on:
# li1/met1..met5 pin purpose (x,5), nwell/pwell pin+label, and the 83/44
# text layer that carries each library cell's own name.
STANDARD_LABEL_LAYERS = {
    (64, 5), (64, 59), (67, 5), (68, 5), (69, 5),
    (70, 5), (71, 5), (72, 5), (83, 44), (122, 16),
}


def mundane_reason(text, layer, texttype, structure, is_pdk_cell):
    """Explain a flagged label as standard tool output, or return None.

    Returning None means: no standard convention accounts for this label,
    so it stays on the candidate-egg list.
    """
    if (layer, texttype) not in STANDARD_LABEL_LAYERS:
        return None
    if not IDENTIFIER.match(text):
        return None
    if is_pdk_cell:
        if (layer, texttype) == (83, 44):
            suffix = structure[len("sky130_fd_sc_hd__"):]
            if text == suffix:
                return "cell-name text on 83/44, standard library content"
            return None
        if text in POWER_NAMES:
            return "power/well pin label, standard library content"
        if CELL_PIN.match(text):
            return "cell pin label, standard library content"
        return None
    # Top cell (or any non-library structure).
    if text in KNOWN_PORTS or KNOWN_PORT_BUS.match(text):
        return "documented top-level port/power label"
    if NET_NAME.match(text):
        return "autogenerated net name from synthesis/P&R"
    return None

# GDS record types this tool cares about.
HEADER, BGNLIB, LIBNAME, UNITS, BGNSTR, STRNAME, ENDLIB = (
    0x00, 0x01, 0x02, 0x03, 0x05, 0x06, 0x04,
)


# ---------------------------------------------------------------------------
# Part 1: header facts, from the raw records. gdstk does not surface the
# BGNLIB/BGNSTR timestamps, so the record stream is walked directly.
# ---------------------------------------------------------------------------

def gds_real8(data):
    """Decode one GDSII 8-byte real: sign, excess-64 exponent, 56-bit mantissa."""
    (word,) = struct.unpack(">Q", data)
    sign = -1.0 if word >> 63 else 1.0
    exponent = ((word >> 56) & 0x7F) - 64
    mantissa = word & ((1 << 56) - 1)
    return sign * (mantissa / float(1 << 56)) * (16.0 ** exponent)


def timestamp_fields(payload):
    """Twelve int16s: modification then access time, each y m d h m s."""
    values = struct.unpack(">12h", payload[:24])
    return values[:6], values[6:]


def render_stamp(fields):
    year, month, day, hour, minute, second = fields
    # GDSII writers disagree on the year convention: some store the year as
    # written, some as year-1900. Render what disambiguates itself.
    if year < 1900:
        year += 1900
    return f"{year:04d}-{month:02d}-{day:02d} {hour:02d}:{minute:02d}:{second:02d}"


def scan_records(path):
    """Walk the raw GDS record stream and pull header facts and timestamps."""
    blob = Path(path).read_bytes()
    facts = {
        "gds_version": None,
        "library_name": None,
        "unit_user": None,       # database unit in user units
        "unit_meters": None,     # database unit in meters
        "bgnlib_modified": None,
        "bgnlib_accessed": None,
        "structures": [],        # (name, modified, accessed) in file order
    }
    offset = 0
    pending_struct_stamp = None
    while offset + 4 <= len(blob):
        (length,) = struct.unpack(">H", blob[offset:offset + 2])
        rectype = blob[offset + 2]
        if length < 4:
            break  # padding at end of tape-format files
        payload = blob[offset + 4:offset + length]
        if rectype == HEADER:
            (facts["gds_version"],) = struct.unpack(">h", payload[:2])
        elif rectype == BGNLIB:
            modified, accessed = timestamp_fields(payload)
            facts["bgnlib_modified"] = render_stamp(modified)
            facts["bgnlib_accessed"] = render_stamp(accessed)
        elif rectype == LIBNAME:
            facts["library_name"] = payload.rstrip(b"\0").decode("ascii", "replace")
        elif rectype == UNITS:
            facts["unit_user"] = gds_real8(payload[:8])
            facts["unit_meters"] = gds_real8(payload[8:16])
        elif rectype == BGNSTR:
            modified, accessed = timestamp_fields(payload)
            pending_struct_stamp = (render_stamp(modified), render_stamp(accessed))
        elif rectype == STRNAME:
            name = payload.rstrip(b"\0").decode("ascii", "replace")
            stamp = pending_struct_stamp or (None, None)
            facts["structures"].append(
                {"name": name, "modified": stamp[0], "accessed": stamp[1]}
            )
            pending_struct_stamp = None
        elif rectype == ENDLIB:
            break
        offset += length
    return facts


# ---------------------------------------------------------------------------
# Part 2: structures and references, through gdstk.
# ---------------------------------------------------------------------------

def classify_structure(name, top_names):
    if name.startswith("sky130_fd_sc_hd__"):
        return "pdk_cell"
    if name.startswith("VIA_") or name.startswith("INTERNAL_") or name in top_names:
        return "known_non_cell"
    return "other"


def structure_inventory(library):
    top_names = {cell.name for cell in library.top_level()}
    refcount = Counter()
    for cell in library.cells:
        for reference in cell.references:
            child = reference.cell
            child_name = child.name if hasattr(child, "name") else str(child)
            repetition = getattr(reference, "repetition", None)
            multiplier = 1
            if repetition is not None:
                try:
                    multiplier = max(1, repetition.size)
                except (AttributeError, TypeError):
                    multiplier = 1
            refcount[child_name] += multiplier

    rows = []
    for cell in library.cells:
        rows.append(
            {
                "name": cell.name,
                "references_to_it": refcount.get(cell.name, 0),
                "class": classify_structure(cell.name, top_names),
                "is_top": cell.name in top_names,
            }
        )
    rows.sort(key=lambda row: (row["class"], row["name"]))
    return rows, sorted(top_names)


# ---------------------------------------------------------------------------
# Part 3: labels and their classification.
# ---------------------------------------------------------------------------

def classify_label(text, layer, texttype):
    """Return (expected, reasons). Expected means: pin layer AND pin-like name."""
    reasons = []
    if (layer, texttype) not in PIN_LABEL_LAYERS:
        reasons.append(f"off-layer ({layer},{texttype}) not in li1(67,5)/met1(68,5)")
    if not IDENTIFIER.match(text):
        reasons.append("text is not a port/net-like identifier")
    if " " in text or len(text.split()) > 1:
        reasons.append("text contains whitespace: reads like a message")
    if len(text) > 32:
        reasons.append(f"text unusually long ({len(text)} chars)")
    return (not reasons), reasons


def label_inventory(library, unit):
    scale = unit / 1e-6  # coordinates to micrometres
    rows = []
    for cell in library.cells:
        is_pdk = cell.name.startswith("sky130_fd_sc_hd__")
        for label in cell.labels:
            expected, reasons = classify_label(label.text, label.layer, label.texttype)
            mundane = None
            if not expected:
                mundane = mundane_reason(
                    label.text, label.layer, label.texttype, cell.name, is_pdk
                )
            rows.append(
                {
                    "structure": cell.name,
                    "text": label.text,
                    "layer": label.layer,
                    "texttype": label.texttype,
                    "x_um": round(label.origin[0] * scale, 4),
                    "y_um": round(label.origin[1] * scale, 4),
                    "expected_pin_label": expected,
                    "flag_reasons": reasons,
                    "mundane_reason": mundane,
                }
            )
    rows.sort(key=lambda row: (row["structure"], row["layer"], row["texttype"],
                               row["x_um"], row["y_um"], row["text"]))
    return rows


# ---------------------------------------------------------------------------
# Reporting.
# ---------------------------------------------------------------------------

def report(target_name, gds_path, out_dir):
    facts = scan_records(gds_path)
    library = gdstk.read_gds(str(gds_path))
    structures, top_names = structure_inventory(library)
    labels = label_inventory(library, library.unit)

    struct_stamps = Counter(
        (row["modified"], row["accessed"]) for row in facts["structures"]
    )
    layer_hist = Counter((row["layer"], row["texttype"]) for row in labels)
    flagged = [row for row in labels if not row["expected_pin_label"]]
    mundane = [row for row in flagged if row["mundane_reason"]]
    unexplained = [row for row in flagged if not row["mundane_reason"]]
    others = [row for row in structures if row["class"] == "other"]
    class_hist = Counter(row["class"] for row in structures)

    print(f"=== {target_name}: {gds_path} ===")
    print(f"library name      {facts['library_name']!r}")
    print(f"gds version       {facts['gds_version']}")
    print(f"units             {facts['unit_user']} user, {facts['unit_meters']} m per db unit")
    print(f"BGNLIB modified   {facts['bgnlib_modified']}")
    print(f"BGNLIB accessed   {facts['bgnlib_accessed']}")
    print(f"structures        {len(structures)} "
          f"(pdk_cell {class_hist.get('pdk_cell', 0)}, "
          f"known_non_cell {class_hist.get('known_non_cell', 0)}, "
          f"other {class_hist.get('other', 0)})")
    print(f"top level         {', '.join(top_names)}")
    print("BGNSTR stamps     " + "; ".join(
        f"{count} structs @ mod {stamp[0]} / acc {stamp[1]}"
        for stamp, count in sorted(struct_stamps.items(), key=lambda kv: -kv[1])
    ))
    if others:
        print("OTHER structure names (not PDK, not VIA_/INTERNAL_/top):")
        for row in others:
            print(f"  {row['name']!r} referenced {row['references_to_it']} times")
    else:
        print("OTHER structure names: none")

    print(f"labels total      {len(labels)}")
    print("label layer histogram:")
    for (layer, texttype), count in sorted(layer_hist.items()):
        marker = "" if (layer, texttype) in PIN_LABEL_LAYERS else "   <-- not a pin layer"
        print(f"  ({layer},{texttype}): {count}{marker}")
    print(f"flagged           {len(flagged)} "
          f"({len(mundane)} mundane by standard convention, "
          f"{len(unexplained)} unexplained)")
    if mundane:
        mundane_hist = Counter(row["mundane_reason"] for row in mundane)
        for reason, count in sorted(mundane_hist.items(), key=lambda kv: -kv[1]):
            print(f"  mundane x{count}: {reason}")
    if unexplained:
        print(f"UNEXPLAINED labels ({len(unexplained)}) -- candidate eggs:")
        for row in unexplained:
            print(f"  {row['structure']}: {row['text']!r} on "
                  f"({row['layer']},{row['texttype']}) at "
                  f"({row['x_um']}, {row['y_um']}) um -- {'; '.join(row['flag_reasons'])}")
    else:
        print("UNEXPLAINED labels: none")

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"labels_{target_name}.json"
    inventory = {
        "target": target_name,
        "gds_path": str(gds_path),
        "header": {key: facts[key] for key in facts if key != "structures"},
        "structure_timestamps": facts["structures"],
        "structures": structures,
        "top_level": top_names,
        "labels": labels,
        "label_layer_histogram": {
            f"{layer},{texttype}": count
            for (layer, texttype), count in sorted(layer_hist.items())
        },
        "flagged_labels": flagged,
        "flagged_mundane": len(mundane),
        "unexplained_labels": unexplained,
        "other_structures": others,
    }
    out_path.write_text(json.dumps(inventory, indent=2))
    print(f"inventory written {out_path}")
    print()
    return inventory


# ---------------------------------------------------------------------------
# Selftest: the classifier must flag a planted message and nothing else.
# ---------------------------------------------------------------------------

def selftest():
    library = gdstk.Library(name="selftest", unit=1e-6, precision=1e-9)
    cell = gdstk.Cell("selftest_top")
    # Innocuous: a pin-like label on li1 (67,5). Must NOT be flagged.
    cell.add(gdstk.Label("clk", (1.0, 2.0), layer=67, texttype=5))
    # Planted: a message on an odd layer. MUST be flagged and unexplained.
    cell.add(gdstk.Label("THE PLANTED EGG", (3.0, 4.0), layer=200, texttype=0))
    # A word posing as an identifier on a pin layer, in the top cell, not a
    # documented port. Not flagged by the layer rule -- but a word that is
    # neither a port nor a net name must land in unexplained, not mundane,
    # if it ever gets flagged; here it is expected_pin_label by the primary
    # rule, so assert the mundane tier would NOT have excused it either.
    library.add(cell)
    pdk = gdstk.Cell("sky130_fd_sc_hd__inv_1")
    # Standard library content: must be flagged (off pin layers) but mundane.
    pdk.add(gdstk.Label("VPB", (0.2, 2.7), layer=64, texttype=5))
    pdk.add(gdstk.Label("inv_1", (0.0, 0.0), layer=83, texttype=44))
    # Planted inside a PDK cell on the cell-name layer, wrong name: must be
    # flagged AND unexplained even though the layer is a standard one.
    pdk.add(gdstk.Label("NOT_THE_CELLNAME", (0.0, 1.0), layer=83, texttype=44))
    library.add(pdk)

    labels = label_inventory(library, library.unit)
    flagged = [row for row in labels if not row["expected_pin_label"]]
    unexplained = [row for row in flagged if not row["mundane_reason"]]
    mundane = [row for row in flagged if row["mundane_reason"]]

    failures = []
    if len(labels) != 5:
        failures.append(f"expected 5 labels in the fixture, saw {len(labels)}")
    if len(flagged) != 4:
        failures.append(f"expected 4 flagged labels, saw {len(flagged)}")
    if sorted(row["text"] for row in unexplained) != [
        "NOT_THE_CELLNAME", "THE PLANTED EGG",
    ]:
        failures.append(
            "unexplained set wrong: "
            + repr(sorted(row["text"] for row in unexplained))
        )
    if sorted(row["text"] for row in mundane) != ["VPB", "inv_1"]:
        failures.append(
            "mundane set wrong: " + repr(sorted(row["text"] for row in mundane))
        )
    planted = [row for row in unexplained if row["text"] == "THE PLANTED EGG"]
    if planted:
        reasons = " ".join(planted[0]["flag_reasons"])
        if "off-layer" not in reasons:
            failures.append("planted label not flagged for its layer")
        if "identifier" not in reasons and "message" not in reasons:
            failures.append("planted label not flagged for its text")
    # The mundane tier must not excuse a word in the top cell that is neither
    # a documented port nor a net name, even on a standard pin layer.
    if mundane_reason("EASTEREGG", 67, 5, "selftest_top", False) is not None:
        failures.append("mundane tier excused an unknown word in the top cell")
    if mundane_reason("n42", 67, 5, "selftest_top", False) is None:
        failures.append("mundane tier rejected a plain net name")

    # The structure classifier, on the same fixture: the top cell is a known
    # non-cell, and a PDK-named cell classifies as pdk_cell.
    if classify_structure("selftest_top", {"selftest_top"}) != "known_non_cell":
        failures.append("top cell not classified as known_non_cell")
    if classify_structure("sky130_fd_sc_hd__inv_1", set()) != "pdk_cell":
        failures.append("PDK cell not classified as pdk_cell")
    if classify_structure("mystery_block", set()) != "other":
        failures.append("unknown name not classified as other")

    if failures:
        for line in failures:
            print(f"SELFTEST FAIL: {line}")
        return 1
    print("SELFTEST PASS: planted labels unexplained, standard content "
          "mundane, pin label passed, structure classes correct (9 checks)")
    return 0


def main(argv):
    if "--selftest" in argv:
        return selftest()
    names = argv or ["puzzle", "warmup"]
    out_dir = REPO / "out" / "eggs"
    for name in names:
        if name in TARGETS:
            report(name, TARGETS[name], out_dir)
        else:
            path = Path(name)
            if not path.exists():
                print(f"no such target or file: {name}")
                return 2
            report(path.stem, path, out_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
