"""Easter-egg hunt, domain B1: the output generator's message space, by simulation.

Feeds a battery of 121-bit input vectors to the puzzle's stage-2 netlist
(out/puzzle/netlist.v) under the PDK's own cell models, replicating the framing
`puzzle/example_inputs.vcd` uses for an attempt, and reports every distinct
(success_ever, rendered message) outcome. Any readable rendering that is
neither the TRY AGAIN family nor the winning message is an egg candidate.

Framing, copied from the VCD (out/puzzle/stimulus.txt derives it):

    3 cycles   rst_n=0 enable=0 I=0     the reset toggle the hint asks for
    1 cycle    rst_n=1 enable=0 I=0     idle row between reset and attempt
    121 cycles rst_n=1 enable=1 I=bit   the attempt, one bit per rising edge
    N cycles   the --after row          extension, so the answer can stream out

The cycle model is tools/sim/harness.py's, verbatim: inputs move while the
clock is low, outputs are sampled before the rising edge, one edge per cycle.
The testbench is generated by harness.clocked_bench so this tool cannot drift
from the pipeline's own cycle conventions. Rendering is stage 7's: 0x00 -> \\0,
0x07 -> \\a, 0x0a -> \\n, x/z -> \\?, \\xNN otherwise, nothing dropped; the
trimmed stream runs from the first non-0x00 byte to the last.

--after policies (the policy AND the exact row are printed with every result):

    idle        rst_n=1 enable=0 I=0. The default. This is the row the VCD
                itself drives after each attempt window, and it is byte
                identical to what stage 7's hold-last produced on the winning
                baseline (whose trace ends with this row).
    hold-last   the final attempt row repeated (enable stays 1).
    zeros       every input 0 -- NOTE this holds rst_n low, i.e. reset.
    port=value  overrides applied to the idle row.

Native toolchain only -- `iverilog` and `vvp` as found on PATH, or wherever
GDS_IVERILOG and GDS_VVP point -- with the exact flags tools/sim/harness.py uses (-g2012 -DFUNCTIONAL
-DUNIT_DELAY=#1, model files listed explicitly, -I per cell directory).
No docker, no container. Simulations run sequentially.

Usage:
    .venv-linux/bin/python tools/egg_output_battery.py --selftest
    .venv-linux/bin/python tools/egg_output_battery.py --only 05,06,07
    .venv-linux/bin/python tools/egg_output_battery.py            # full battery
    .venv-linux/bin/python tools/egg_output_battery.py --scratch /tmp/xyz

Writes out/eggs/output_battery.json.
"""

import json
import os
import random
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(HERE, "sim"))
sys.path.insert(0, HERE)
os.chdir(REPO)

import harness                                                  # noqa: E402
from run import model_files                                     # noqa: E402

# Resolved rather than hard coded. This used to name one machine's
# oss-cad-suite install, which meant the tool could not run for anybody who
# cloned the repository -- the author's own path, shipped as if it were an
# interface. PATH first, then an override for a toolchain installed somewhere
# the shell does not know about.
IVERILOG = os.environ.get("GDS_IVERILOG") or shutil.which("iverilog")
VVP = os.environ.get("GDS_VVP") or shutil.which("vvp")
NETLIST = os.path.join("out", "puzzle", "netlist.v")
STIMULUS = os.path.join("out", "puzzle", "stimulus.txt")
SOLUTION = os.path.join("out", "puzzle", "solution_post_reset.json")
OUT_JSON = os.path.join("out", "eggs", "output_battery.json")
PROBE_JSON = os.path.join("out", "eggs", "output_battery_probe.json")

BITS = 121          # attempt length, from the VCD's enable windows
RESET_CYCLES = 3    # rst_n low rows before each attempt, from the VCD
IDLE_AFTER_RESET = 1  # rows between reset release and enable rise, from the VCD
EXTEND = 64         # extension cycles past the frame; message is 15 bytes,
                    # TRY AGAIN is 9, so 64 is 4x margin
GAP = 35            # enable-low rows between the VCD's two attempts
GAP_RESET_AT = 31   # ...with rst_n low at gap rows 31, 32, 33 (mirrors start)
RANDOM_SEED = 20260905
N_RANDOM = 20

# Stage 7's escaping, restated here and proven equal to stage7_output's own
# escape() over all 256 bytes and None by --selftest.
NAMED = {0x00: r"\0", 0x07: r"\a", 0x08: r"\b", 0x09: r"\t", 0x0a: r"\n",
         0x0b: r"\v", 0x0c: r"\f", 0x0d: r"\r", 0x1b: r"\e", 0x5c: "\\\\"}
IDLE_BYTE = 0


def escape(byte):
    if byte is None:
        return r"\?"
    if byte in NAMED:
        return NAMED[byte]
    if 0x20 <= byte < 0x7f:
        return chr(byte)
    return f"\\x{byte:02x}"


def render(values):
    return "".join(escape(v) for v in values)


def trim(values, idle=IDLE_BYTE):
    live = [i for i, v in enumerate(values) if v is not None and v != idle]
    return (live[0], live[-1]) if live else None


def printable_fraction(byte_values):
    """Fraction of defined bytes in 0x20..0x7e. None if no defined bytes."""
    defined = [v for v in byte_values if v is not None]
    if not defined:
        return None
    return sum(1 for v in defined if 0x20 <= v < 0x7f) / len(defined)


def after_row(policy):
    """(row, description). See module docstring for the policies."""
    idle = {"rst_n": 1, "enable": 0, "I": 0}
    if policy == "idle":
        return idle, ("rst_n=1 enable=0 I=0, the row the VCD drives after "
                      "every attempt (equals stage 7's hold-last on the "
                      "winning baseline)")
    if policy == "zeros":
        return {"rst_n": 0, "enable": 0, "I": 0}, ("every input 0 -- rst_n "
                                                   "held low, i.e. in reset")
    if policy == "hold-last":
        return None, "the final attempt row repeated (enable stays 1)"
    row = dict(idle)
    named = []
    for item in policy.split(","):
        if "=" not in item:
            raise ValueError(f"--after {policy!r}: expected idle, hold-last, "
                             f"zeros, or port=value pairs")
        port, text = item.split("=", 1)
        port, text = port.strip(), text.strip()
        if port not in row:
            raise ValueError(f"--after {policy!r}: {port!r} is not an input; "
                             f"inputs are {sorted(row)}")
        row[port] = int(text, 0)
        named.append(port)
    return row, ("the idle row with "
                 + ", ".join(f"{p}={row[p]}" for p in named) + " overridden")


def attempt_rows(vector):
    """The rows one attempt drives: reset toggle, idle, then the 121 bits."""
    if len(vector) != BITS or set(vector) - {"0", "1"}:
        raise ValueError(f"vector must be {BITS} bits of 0/1, got "
                         f"{len(vector)} chars")
    rows = [{"rst_n": 0, "enable": 0, "I": 0} for _ in range(RESET_CYCLES)]
    rows += [{"rst_n": 1, "enable": 0, "I": 0} for _ in range(IDLE_AFTER_RESET)]
    rows += [{"rst_n": 1, "enable": 1, "I": int(b)} for b in vector]
    return rows


def frame_single(vector, extend, policy):
    """One attempt plus extension. Returns (rows, notes, after_row_used)."""
    rows = attempt_rows(vector)
    row, _ = after_row(policy)
    if row is None:                      # hold-last
        row = dict(rows[-1])
    notes = {len(rows) - 1: "<- last attempt cycle",
             len(rows): "<- extension begins"}
    rows += [dict(row) for _ in range(extend)]
    return rows, notes, row


def frame_double(vector, extend, policy, mid_reset):
    """Two attempts back to back. mid_reset replicates the VCD's inter-attempt
    reset toggle (3 rows of rst_n=0 at gap offset 31, then 1 idle row);
    without it the same 35 gap rows are driven with rst_n held high."""
    rows = attempt_rows(vector)
    first_end = len(rows) - 1
    for g in range(GAP):
        low = mid_reset and GAP_RESET_AT <= g < GAP_RESET_AT + RESET_CYCLES
        rows.append({"rst_n": 0 if low else 1, "enable": 0, "I": 0})
    second_start = len(rows)
    rows += [{"rst_n": 1, "enable": 1, "I": int(b)} for b in vector]
    row, _ = after_row(policy)
    if row is None:
        row = dict(rows[-1])
    notes = {first_end: "<- attempt 1 ends",
             second_start: "<- attempt 2 begins",
             len(rows) - 1: "<- last attempt cycle",
             len(rows): "<- extension begins"}
    rows += [dict(row) for _ in range(extend)]
    return rows, notes, row


def build_bench(rows, notes):
    """The testbench text for one frame, via the pipeline's own generator."""
    top, module_ports = harness.module_of(NETLIST)
    ports = harness.port_widths(NETLIST)
    widths = {"I": 1, "enable": 1, "rst_n": 1}
    watch = {n: i["width"] for n, i in ports.items()
             if i["direction"] == "output"}
    return harness.clocked_bench(top, module_ports, ["clk"], widths,
                                 rows, watch, notes), watch


def simulate(item_id, rows, notes, scratch, compile_env):
    """Compile and run one frame natively. Returns the parsed sample rows."""
    bench_text, watch = build_bench(rows, notes)
    bench_path = os.path.join(scratch, f"tb_{item_id}.v")
    vvp_path = os.path.join(scratch, f"sim_{item_id}.vvp")
    with open(bench_path, "w", encoding="utf-8") as handle:
        handle.write(bench_text)
    cells, files, includes, missing = compile_env
    if missing:
        raise RuntimeError("no model in the PDK cache for: "
                           + ", ".join(missing))
    build = [IVERILOG, "-g2012", "-DFUNCTIONAL", "-DUNIT_DELAY=#1",
             "-o", vvp_path]
    for d in includes:
        build += ["-I", d]
    build += [bench_path, NETLIST] + files
    done = subprocess.run(build, capture_output=True, text=True, cwd=REPO)
    if done.returncode != 0:
        raise RuntimeError(f"iverilog failed for {item_id}:\n"
                           + done.stdout + done.stderr)
    done = subprocess.run([VVP, vvp_path], capture_output=True, text=True,
                          cwd=REPO)
    os.remove(vvp_path)
    if done.returncode != 0:
        raise RuntimeError(f"vvp failed for {item_id}:\n"
                           + done.stdout + done.stderr)
    observed = harness.samples(done.stdout + done.stderr)
    if len(observed) != len(rows):
        raise RuntimeError(f"{item_id}: {len(observed)} samples for "
                           f"{len(rows)} rows")
    return observed, watch


def analyse(item_id, kind, rows, observed):
    """One record per run: success profile, byte stream, renderings."""
    succ = [s.get("success") for s in observed]
    success_bits = "".join(b if b in "01" else "?" for b in succ)
    high = [i for i, b in enumerate(succ) if b == "1"]
    values = [harness.value(s["O"]) for s in observed]
    span = trim(values)
    trimmed_vals = values[span[0]:span[1] + 1] if span else []
    return {
        "id": item_id,
        "kind": kind,
        "cycles": len(rows),
        "success_ever": bool(high),
        "success_first_cycle": high[0] if high else None,
        "success_high_cycles": len(high),
        "o_defined_cycles": sum(1 for v in values if v is not None),
        "trimmed_first_cycle": span[0] if span else None,
        "trimmed_last_cycle": span[1] if span else None,
        "trimmed_bytes": trimmed_vals,
        "trimmed_text": render(trimmed_vals) if span else "",
        "printable_fraction_trimmed": printable_fraction(trimmed_vals),
        "success_bits": success_bits,
    }


def vectors_from_artifacts():
    """The VCD's two attempts and the winning vector, derived not hardcoded."""
    lines = [l.strip() for l in open(STIMULUS, encoding="utf-8") if l.strip()]
    en = "".join(l[1] for l in lines)
    I = "".join(l[2] for l in lines)
    windows, start = [], None
    for i, b in enumerate(en + "0"):
        if b == "1" and start is None:
            start = i
        elif b != "1" and start is not None:
            windows.append(I[start:i])
            start = None
    if len(windows) != 2 or any(len(w) != BITS for w in windows):
        raise RuntimeError(f"{STIMULUS}: expected two {BITS}-bit enable "
                           f"windows, found {[len(w) for w in windows]}")
    with open(SOLUTION, encoding="utf-8") as handle:
        sol = json.load(handle)
    win = "".join(str(r["I"]) for r in sol["trace"] if r["enable"] == 1)
    if len(win) != BITS:
        raise RuntimeError(f"{SOLUTION}: winning window is {len(win)} bits")
    return windows[0], windows[1], win


def battery_items():
    """The full battery, in the order the task lists it."""
    vcd1, vcd2, win = vectors_from_artifacts()
    items = [
        ("01-all-zeros", "single", "0" * BITS),
        ("02-all-ones", "single", "1" * BITS),
        ("03-alt-01", "single", ("01" * BITS)[:BITS]),
        ("04-alt-10", "single", ("10" * BITS)[:BITS]),
        ("05-vcd-attempt-1", "single", vcd1),
        ("06-vcd-attempt-2", "single", vcd2),
        ("07-winning", "single", win),
    ]
    for i in range(BITS):
        flipped = win[:i] + ("1" if win[i] == "0" else "0") + win[i + 1:]
        items.append((f"08-flip-{i:03d}", "single", flipped))
    items.append(("09-winning-complement", "single",
                  "".join("1" if b == "0" else "0" for b in win)))
    items.append(("10-winning-reversed", "single", win[::-1]))
    rng = random.Random(RANDOM_SEED)
    for i in range(N_RANDOM):
        items.append((f"11-rand-{i:02d}", "single",
                      "".join(str(rng.getrandbits(1)) for _ in range(BITS))))
    items.append(("12-double-no-mid-reset", "double-noreset", win))
    items.append(("13-double-with-mid-reset", "double-reset", win))
    return items, win


def frame_for(kind, vector, extend, policy):
    if kind == "single":
        return frame_single(vector, extend, policy)
    if kind == "double-noreset":
        return frame_double(vector, extend, policy, mid_reset=False)
    if kind == "double-reset":
        return frame_double(vector, extend, policy, mid_reset=True)
    raise ValueError(kind)


def run_battery(scratch, extend, policy, only=None, probes=None):
    os.makedirs(scratch, exist_ok=True)
    os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)
    # A partial or probe run must not overwrite the full battery's deliverable.
    out_path = OUT_JSON if (only is None and not probes) else PROBE_JSON
    row, described = after_row(policy)
    print(f"netlist    {NETLIST}")
    print(f"toolchain  {IVERILOG} (native, no container)")
    print(f"framing    {RESET_CYCLES} reset rows, {IDLE_AFTER_RESET} idle row, "
          f"{BITS} attempt bits, {extend} extension rows")
    print(f"--after    {policy}: {described}")
    if row is not None:
        print(f"           row: {row}")
    print(f"--extend   {extend}")

    compile_env = model_files(NETLIST)
    cells, files, includes, missing = compile_env
    print(f"models     {len(files)} files for {len(cells)} cell types, "
          f"missing {len(missing)}\n")

    items, win = battery_items()
    if only:
        wanted = {w.strip() for w in only.split(",")}
        items = [it for it in items
                 if it[0] in wanted or it[0].split("-")[0] in wanted]
        if not items:
            sys.exit(f"--only {only!r} matches no battery item")
    if probes:
        # Anti-pareidolia controls: arbitrary named vectors through the same
        # frame, e.g. one bit away from all-zeros. Replaces the battery.
        items = []
        for spec in probes:
            name, _, bits = spec.partition(":")
            items.append((f"probe-{name}", "single", bits))

    for item_id, _, bits in items:
        if len(bits) != BITS or set(bits) - {"0", "1"}:
            sys.exit(f"{item_id}: vector must be {BITS} bits of 0/1")

    # Baseline gate first: items 05, 06, 07 must reproduce known behaviour
    # before anything else in the battery is worth trusting.
    ordered = ([it for it in items if it[0].startswith(("05", "06", "07"))]
               + [it for it in items
                  if not it[0].startswith(("05", "06", "07"))])

    records = []
    for index, (item_id, kind, vector) in enumerate(ordered):
        rows, notes, used_row = frame_for(kind, vector, extend, policy)
        observed, _ = simulate(item_id, rows, notes, scratch, compile_env)
        record = analyse(item_id, kind, rows, observed)
        record["vector"] = vector
        record["after_row_used"] = used_row
        records.append(record)
        print(f"[{index + 1:>3}/{len(ordered)}] {item_id:<28} "
              f"success={'YES' if record['success_ever'] else 'no ':<3} "
              f"msg={record['trimmed_text']!r}")

        if item_id == "05-vcd-attempt-1" or item_id == "06-vcd-attempt-2":
            if record["success_ever"] or record["trimmed_text"] != "TRY AGAIN":
                print("\nBASELINE FAILURE: the VCD attempt did not reproduce "
                      "TRY AGAIN with success low. Stopping; the harness "
                      "cannot be trusted.")
                return 2, records
        if item_id == "07-winning":
            if (not record["success_ever"]
                    or record["trimmed_text"] != "(* TWO STARS *)"):
                print("\nBASELINE FAILURE: the winning vector did not "
                      "reproduce '(* TWO STARS *)' with success high. "
                      "Stopping; the harness cannot be trusted.")
                return 2, records

    # Distinct outcomes.
    groups = {}
    for r in sorted(records, key=lambda r: r["id"]):
        key = (r["success_ever"], r["trimmed_text"])
        groups.setdefault(key, []).append(r["id"])
    outcome_list = [
        {"success_ever": k[0], "message": k[1], "count": len(v),
         "items": v if len(v) <= 12 else v[:12] + [f"... {len(v) - 12} more"]}
        for k, v in sorted(groups.items(),
                           key=lambda kv: (-len(kv[1]), kv[0][1]))]

    result = {
        "netlist": NETLIST,
        "toolchain": {"iverilog": IVERILOG, "vvp": VVP,
                      "flags": "-g2012 -DFUNCTIONAL -DUNIT_DELAY=#1",
                      "container": None},
        "framing": {"reset_cycles": RESET_CYCLES,
                    "idle_after_reset": IDLE_AFTER_RESET,
                    "attempt_bits": BITS,
                    "extend": extend,
                    "after_policy": policy,
                    "after_row": row if row is not None else "hold-last",
                    "gap_rows_double": GAP,
                    "gap_reset_offset": GAP_RESET_AT,
                    "cycle_model": "tools/sim/harness.py clocked_bench: "
                                   "inputs move while clk low, outputs "
                                   "sampled before the rising edge"},
        "winning_vector": win,
        "random_seed": RANDOM_SEED,
        "distinct_outcomes": outcome_list,
        "runs": records,
    }
    with open(out_path, "w", encoding="utf-8") as handle:
        json.dump(result, handle, indent=1)

    print(f"\ndistinct (success_ever, message) outcomes: {len(outcome_list)}")
    for o in outcome_list:
        print(f"  success={'YES' if o['success_ever'] else 'no '} "
              f"x{o['count']:<4} {o['message']!r}")
    print(f"\nwrote {out_path}")
    return 0, records


def selftest():
    failures = []

    def check(name, ok):
        print(f"  {'pass' if ok else 'FAIL'}  {name}")
        if not ok:
            failures.append(name)

    print("selftest (no simulation is run)")

    # 1. The testbench generator is deterministic: same vector twice gives a
    #    byte-identical testbench, and a different vector gives a different one.
    v1 = ("01" * BITS)[:BITS]
    v2 = ("10" * BITS)[:BITS]
    rows_a, notes_a, _ = frame_single(v1, 8, "idle")
    rows_b, notes_b, _ = frame_single(v1, 8, "idle")
    bench_a, _ = build_bench(rows_a, notes_a)
    bench_b, _ = build_bench(rows_b, notes_b)
    check("same vector twice -> byte-identical testbench", bench_a == bench_b)
    rows_c, notes_c, _ = frame_single(v2, 8, "idle")
    bench_c, _ = build_bench(rows_c, notes_c)
    check("different vector -> different testbench", bench_a != bench_c)

    # 2. The renderer escapes exactly the way stage 7 (and so verify_output.py,
    #    which imports stage 7's escape) expects: proven by comparing against
    #    stage7_output's own function over every byte and None.
    import stage7_output
    parity = all(escape(b) == stage7_output.escape(b)
                 for b in list(range(256)) + [None])
    check("escape() equals stage7_output.escape() on 0..255 and None", parity)
    check(r"0x07 -> \a", escape(0x07) == "\\a")
    check(r"0x0a -> \n", escape(0x0a) == "\\n")
    check(r"0x00 -> \0", escape(0x00) == "\\0")
    check(r"x/z -> \?", escape(None) == "\\?")
    check("printable stays itself", escape(0x41) == "A")

    # 3. Trim convention: first non-idle byte to the last.
    check("trim finds the live span",
          trim([0, 0, 65, 0, 66, 0]) == (2, 4))
    check("trim of all idle is None", trim([0, 0, 0]) is None)
    check("trim treats None as idle", trim([None, None]) is None)

    # 4. Frame shape: the single frame is reset + idle + bits + extension,
    #    and the two double frames differ in exactly the 3 mid-reset rows.
    rows, _, _ = frame_single(v1, 8, "idle")
    check("single frame length",
          len(rows) == RESET_CYCLES + IDLE_AFTER_RESET + BITS + 8)
    check("reset rows hold rst_n low",
          all(r["rst_n"] == 0 for r in rows[:RESET_CYCLES]))
    check("attempt rows carry the vector",
          "".join(str(r["I"]) for r in rows if r["enable"] == 1) == v1)
    d_no, _, _ = frame_double(v1, 8, "idle", mid_reset=False)
    d_yes, _, _ = frame_double(v1, 8, "idle", mid_reset=True)
    diffs = [i for i, (a, b) in enumerate(zip(d_no, d_yes)) if a != b]
    check("double frames same length", len(d_no) == len(d_yes))
    check("mid reset differs in exactly the 3 reset rows",
          len(diffs) == RESET_CYCLES
          and all(d_yes[i]["rst_n"] == 0 and d_no[i]["rst_n"] == 1
                  for i in diffs))
    check("both double frames carry the vector twice",
          "".join(str(r["I"]) for r in d_no if r["enable"] == 1) == v1 * 2)

    # 5. Battery vectors come from the artifacts and have the right shape.
    vcd1, vcd2, win = vectors_from_artifacts()
    check("three derived vectors are 121 bits",
          all(len(v) == BITS for v in (vcd1, vcd2, win)))
    check("winning vector differs from both VCD attempts",
          win != vcd1 and win != vcd2)
    items, _ = battery_items()
    check(f"battery is {7 + BITS + 2 + N_RANDOM + 2} items",
          len(items) == 7 + BITS + 2 + N_RANDOM + 2)
    rng_a = random.Random(RANDOM_SEED)
    rng_b = random.Random(RANDOM_SEED)
    check("random vectors are seed-deterministic",
          [rng_a.getrandbits(1) for _ in range(500)]
          == [rng_b.getrandbits(1) for _ in range(500)])

    print(f"\nselftest: {'PASS' if not failures else 'FAIL'} "
          f"({len(failures)} failure(s))")
    return 1 if failures else 0


def main(argv):
    scratch = os.path.join("out", "eggs", "_build")
    extend, policy, only, probes = EXTEND, "idle", None, []
    rest = list(argv)
    if rest and rest[0] == "--selftest":
        return selftest()
    while rest:
        item = rest.pop(0)
        if item == "--scratch":
            scratch = rest.pop(0)
        elif item == "--extend":
            extend = int(rest.pop(0))
        elif item == "--after":
            policy = rest.pop(0)
        elif item == "--only":
            only = rest.pop(0)
        elif item == "--probe":
            probes.append(rest.pop(0))
        else:
            sys.exit("usage: egg_output_battery.py [--selftest] "
                     "[--scratch DIR] [--extend N] [--after POLICY] "
                     "[--only 05,06,07] [--probe name:BITS ...]")
    code, _ = run_battery(scratch, extend, policy, only, probes)
    return code


if __name__ == "__main__":
    # Said here rather than left to a None creeping into a subprocess call and
    # surfacing as an unreadable TypeError three functions down.
    for name, found in (("iverilog", IVERILOG), ("vvp", VVP)):
        if not found:
            sys.exit(f"{name} not found. Put it on PATH, or point "
                     f"GDS_{name.upper()} at it. This battery runs the "
                     f"simulator natively and does not use the containers.")
    sys.exit(main(sys.argv[1:]))
