"""Everything a person needs beside the layout, and no reading of it.

Stage 4 refuses to commit to a register partition, and `docs/04` says plainly
that the disagreement is the residue and a person reads it. This assembles what
that person would otherwise assemble by hand: which flops `success` actually
depends on, how the candidate pieces sit against that boundary, where the flops
are on the die, and what the winning input looks like in a few groupings.

**It names nothing.** The line between a measurement and a reading is drawn
here: a sentence this file may print is one a program produced and a re-run can
check. A sentence assigning purpose or meaning -- "this block is a counter",
"these bits are the key" -- is a reading, belongs to the author, and is not
here. Every table carries an empty `reading` column for exactly that reason.

    python tools/reading_aid.py puzzle      # -> out/puzzle/reading-aid.md
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import stage4_registers
import stage6_invert


def load(target, name):
    path = os.path.join("out", target, name)
    if not os.path.exists(path):
        sys.exit(f"{path} missing")
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def flop_of_bit(registers, label):
    """`R0[57]` -> the instance name, using the register's own bit order."""
    name, _, rest = label.partition("[")
    index = int(rest.rstrip("]"))
    for row in registers["registers"]:
        if row["register"] == name:
            return row["flops"][index]
    return None


def transitive_flops(design, graph, seeds):
    """Flops reachable backwards from these, across cycle boundaries.

    One cone stops at a flop output. Following each of those flops' own data
    cones and repeating to a fixpoint gives every bit of state that can reach
    the seed given enough cycles, which is the question a reader asks about
    `success` and not the question one cone answers.
    """
    q_of = {record["q"]: instance
            for instance, record in graph["flipflops"].items()}
    reached, frontier = set(), list(seeds)
    while frontier:
        instance = frontier.pop()
        if instance in reached:
            continue
        reached.add(instance)
        record = graph["flipflops"][instance]
        for role in ("data", "reset", "set"):
            net = record.get(role)
            if not net:
                continue
            for reachable in design.support(net):
                found = q_of.get(reachable)
                if found and found not in reached:
                    frontier.append(found)
    return reached


def main(target):
    graph = load(target, "graph.json")
    registers = load(target, "registers.json")
    cone = load(target, "cone.json")
    solution = load(target, "solution.json")
    design = stage6_invert.Design(graph)

    rows = {row["register"]: row for row in registers["registers"]}
    all_flops = sorted(graph["flipflops"])

    # --- the boundary -------------------------------------------------------
    direct = {flop_of_bit(registers, b) for b in cone["support"]}
    direct.discard(None)
    reachable = transitive_flops(design, graph,
                                 {cone["root"].split(".")[0]} | direct)

    out = []
    w = out.append
    w("# Reading aid\n")
    w(f"Target `{target}`. Generated by `tools/reading_aid.py`; re-running it "
      f"reproduces this file.\n")
    w("Every number here came from a program and can be checked by re-running "
      "it. Nothing here\nsays what any of it *is*. The `reading` columns are "
      "empty on purpose: that column is the\nauthor's, and it is the only one "
      "this file will not fill in.\n")

    w("## 1. What `success` depends on\n")
    w(f"Cone root `{cone['root']}`, {cone['cells']} cells over "
      f"{len(cone['support'])} boundary signals.\n")
    w(f"- flops named directly by the cone: **{len(direct)}** of "
      f"{len(all_flops)}")
    w(f"- flops reachable across cycles (fixpoint over data, reset and set "
      f"cones): **{len(reachable)}** of {len(all_flops)}")
    outside = [f for f in all_flops if f not in reachable]
    w(f"- flops no number of cycles connects to `success`: **{len(outside)}**"
      + (f" (`{'`, `'.join(outside)}`)" if 0 < len(outside) <= 12 else ""))
    w("")

    w("| register | width | flops in cone | flops transitively | reading |")
    w("|---|---|---|---|---|")
    for name, row in rows.items():
        members = set(row["flops"])
        w(f"| {name} | {row['width']} | {len(members & direct)} | "
          f"{len(members & reachable)} | |")
    w("")

    # --- the eleven pieces --------------------------------------------------
    pieces = registers.get("candidate_splits", {}).get("R0") or []
    w("## 2. R0's candidate pieces against that boundary\n")
    w("Stage 4 reports these and does not apply them. Each row says whether the "
      "piece sits\nwholly inside the cone's flop set, wholly outside, or is cut "
      "by it.\n")
    w("| # | size | in cone | outside | verdict | bit_order | reading |")
    w("|---|---|---|---|---|---|---|")
    inside_total = 0
    for index, piece in enumerate(pieces):
        members = set(piece)
        inside = members & direct
        verdict = ("wholly inside" if len(inside) == len(members)
                   else "wholly outside" if not inside else "**split**")
        if len(inside) == len(members):
            inside_total += len(members)
        order = order_of(design, graph, piece)
        w(f"| {index} | {len(piece)} | {len(inside)} | "
          f"{len(members) - len(inside)} | {verdict} | {order} | |")
    w("")
    sizes = [len(p) for p in pieces]
    split_inside = sum(len(set(p) & direct) for p in pieces
                       if 0 < len(set(p) & direct) < len(p))
    w(f"Piece sizes: `{sizes}`, summing to {sum(sizes)}.")
    w("")
    w("Membership arithmetic, which is the check worth doing because the "
      "pieces were derived\nfrom control and flow and the cone was derived "
      "from neither:\n")
    w(f"- pieces lying **wholly inside** the cone: {inside_total} flops")
    w(f"- flops contributed by pieces the cone **cuts**: {split_inside}")
    w(f"- total: **{inside_total + split_inside}**, against the "
      f"**{len(direct)}** the cone names")
    agree = inside_total + split_inside == len(direct)
    w("")
    w(f"These {'agree' if agree else '**do not agree, which is a finding**'}. "
      + ("A partition derived from control and flow lands on a boundary "
         "derived from\nneither, to within the pieces listed as cut above."
         if agree else ""))
    w("")

    # --- placement ----------------------------------------------------------
    w("## 3. Where the flops sit\n")
    try:
        positions = stage4_registers.placements(target)
        clusters = stage4_registers.spatial_groups(graph, positions)
        w("Single linkage at `LINK_ROWS = 3`, the recorded threshold. "
          "One parameter fitted to one\ndata point, the warm up, and said here "
          "rather than hidden.\n")
        w("A cluster's key is its control signature and a seed flop; both are "
          "shown as the\nsignature's reset and set nets, which is the part a "
          "reader can act on.\n")
        w("| # | flops | in cone | reset | set | bbox um (x / y) | reading |")
        w("|---|---|---|---|---|---|---|")
        ordered = sorted(clusters.items(), key=lambda kv: -len(kv[1]))
        for index, (key, members) in enumerate(ordered):
            signature = key[0] if isinstance(key, tuple) else ()
            reset = signature[2] if len(signature) > 3 else "--"
            preset = signature[6] if len(signature) > 6 else "--"
            w(f"| {index} | {len(members)} | {len(set(members) & direct)} | "
              f"{reset or '--'} | {preset or '--'} | "
              f"{bbox(positions, members)} | |")
        w("")
        w("Threshold profile, cluster sizes at each link distance:\n")
        w("| rows | sizes |")
        w("|---|---|")
        for link, group_sizes in stage4_registers.spatial_profile(graph,
                                                                  positions):
            w(f"| {link} | `{group_sizes}` |")
        w("")
    except Exception as error:                                # noqa: BLE001
        w(f"Placement profile unavailable: {error}\n")

    # --- structure ----------------------------------------------------------
    w("## 4. Register structure\n")
    w("| register | width | cell | reset | set | hold | bit_order | reading |")
    w("|---|---|---|---|---|---|---|---|")
    for name, row in rows.items():
        order = row["bit_order"] or {}
        cells = "`, `".join(sorted(row["cells"]))
        reset = row["reset"] or "--"
        if row["reset"]:
            reset = f"{reset} ({row['reset_level']})"
        preset = row["set"] or "--"
        if row["set"]:
            preset = f"{preset} ({row['set_level']})"
        w(f"| {name} | {row['width']} | `{cells}` | {reset} | {preset} | "
          f"{row['hold'] or '--'} | {order.get('method') or 'none'} | |")
    w("")
    for name, row in rows.items():
        why = (row["bit_order"] or {}).get("why")
        if why:
            w(f"- `{name}` bit order: {why}")
    w("")
    w(f"Dependency edges: `{json.dumps(registers.get('edges', {}))}`\n")

    # --- two yes matrix -----------------------------------------------------
    w("## 5. Two independent votes per piece\n")
    w("Structure is the control signature and the flow; placement reads no "
      "wire at all. A piece\nthe two agree on is a piece two unrelated "
      "measurements found.\n")
    w("| # | size | structure says | placement says | agree | reading |")
    w("|---|---|---|---|---|---|")
    try:
        positions = stage4_registers.placements(target)
        clusters = stage4_registers.spatial_groups(graph, positions)
        for index, piece in enumerate(pieces):
            members = set(piece)
            hit = [k for k, v in clusters.items() if set(v) & members]
            same = (len(hit) == 1
                    and set(clusters[hit[0]]) == members)
            w(f"| {index} | {len(piece)} | one refinement piece | "
              f"{len(hit)} cluster(s){'' if not hit else ', ' + ('exact' if same else 'partial')} | "
              f"{'yes' if same else 'no'} | |")
    except Exception as error:                                # noqa: BLE001
        w(f"| -- | -- | -- | unavailable: {error} | -- | |")
    w("")

    # --- the input ----------------------------------------------------------
    w("## 6. The winning input, shown several ways\n")
    trace = solution["trace"]
    bits = [row.get("I", 0) for row in trace]
    enabled = [row.get("I", 0) for row in trace if row.get("enable")]
    w(f"Trace is {len(trace)} cycles; `success` rises at cycle "
      f"{solution['property']['cycle']}.")
    w(f"`I` is one bit, so the input is serial. Cycles with `enable` high: "
      f"**{len(enabled)}**.\n")
    for label, stream in (("every cycle", bits), ("enable high only", enabled)):
        w(f"**{label}**, {len(stream)} bits:\n")
        w("```")
        w("".join(str(b) for b in stream))
        w("```")
        for size in (7, 8):
            w(f"grouped by {size}, most significant first:\n")
            w("```")
            w(grouped(stream, size))
            w("```")
    w("Shown, not read. Whether any grouping means anything is the author's "
      "call.\n")

    w("---\n")
    w("Empty `reading` columns are the point of this file.")

    path = os.path.join("out", target, "reading-aid.md")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out) + "\n")
    print(f"wrote {path}, {len(out)} lines")
    print(f"  cone names {len(direct)} flops, "
          f"{len(reachable)} reachable transitively, "
          f"{len(outside)} unreachable")
    print(f"  {len(pieces)} candidate pieces, sizes {sizes}")
    return 0


def order_of(design, graph, piece):
    """Whether these flops form a chain by D <- Q, reported not interpreted."""
    q_of = {graph["flipflops"][f]["q"]: f for f in piece}
    edges = 0
    for flop in piece:
        data = graph["flipflops"][flop].get("data")
        if not data:
            continue
        if any(net in q_of for net in design.support(data)):
            edges += 1
    return f"{edges}/{len(piece)} read another member"


def bbox(positions, members):
    points = [positions[f] for f in members if f in positions]
    if not points:
        return "--"
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    return (f"{min(xs):.1f}..{max(xs):.1f} x {min(ys):.1f}..{max(ys):.1f}")


def grouped(stream, size):
    chunks = ["".join(str(b) for b in stream[i:i + size])
              for i in range(0, len(stream), size)]
    lines = []
    for chunk in chunks:
        if len(chunk) < size:
            lines.append(f"{chunk:<{size}}  (short, {len(chunk)} bits)")
            continue
        value = int(chunk, 2)
        printable = chr(value) if 32 <= value < 127 else "."
        lines.append(f"{chunk}  0x{value:02x}  {value:>3}  {printable}")
    return "\n".join(lines)


if __name__ == "__main__":
    args = [a for a in sys.argv[1:]]
    if len(args) != 1:
        sys.exit("usage: python tools/reading_aid.py <target>")
    sys.exit(main(args[0]))
