"""Stage 3, normalisation. A gate level netlist to an annotated graph.

Input.  `out/<target>/netlist.v` from stage 2.
Output. `out/<target>/graph.json`, and `out/<target>/graph.v` written back out
        of the graph so the round trip can be simulated.

Stage 2 produced a netlist that is correct and unreadable: 738 boxes and 723
wires, none of whose names mean anything. This stage does not try to understand
it. It attaches the structural facts that later stages need in order to look for
patterns, and nothing that requires a guess.

What gets derived, following `docs/solver-pipeline.md`:

  - clock nets, from fanout into pins the LEF declares USE CLOCK
  - reset and set nets, the same way
  - a flip flop inventory: clock, reset, set, data source, and where an enable
    is implemented in logic rather than by a pin, which mux does it
  - primary inputs and outputs
  - constant nets, from the cells that generate constants
  - combinational cone membership per net

Yosys does the reading. It is the standard tool, it will be needed again in
stages 4 and 6 for the SMT2 and CNF exports, and hand-parsing Verilog to save a
container is a trade nobody wins.

What Yosys is *not* asked to do is infer the cells. Their interfaces come from a
blackbox library generated here from the PDK's own LEF, so the pin directions in
the graph are the same ones stage 2 emitted the netlist with, from the same
source. The alternative, reading the behavioural cell models, would make this
stage depend on those models parsing under a second tool for no gain.

Verification is a round trip: the graph is written back to Verilog and has to
pass stage 2's simulation unchanged.

Usage:
    python tools/stage3_graph.py warmup
    python tools/sim/run.py warmup --netlist out/warmup/graph.v
"""

import json
import os
import re
import subprocess
import sys
from collections import Counter, defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import liberty
from common.lef import functional_pins, load as load_lef
from stage1_cells import PDK_DIR, TARGETS

IMAGE = "gds-teardown-eda:latest"

# Pin roles come from liberty, which states them functionally:
#
#     ff (IQ, IQ_N) { clocked_on : CLK;  next_state : D;  clear : !RESET_B; }
#
# An earlier version derived them from the LEF's USE CLOCK marker plus the cell
# name. Measured against liberty afterwards, the two sources score differently.
# USE CLOCK turned out to agree with liberty's `clock` on all 429 cells in this
# library, so that half was sound. The cell name was not: `dfbbp_1` and five
# others carry both RESET_B and SET_B, and no reading of `dfr` against `dfs`
# survives that. Reset and set are read from `clear` and `preset`.
#
# The name is still consulted, as a cross check that reports rather than
# decides. Two sources agreeing is worth something; one source and a habit is
# not.
CELL_NAME_MARK = {"reset": "r", "set": "s"}

BUS_BIT = re.compile(r"^(?P<base>.+)\[(?P<index>\d+)\]$")


def blackbox_library(cells, lef, path):
    """Verilog interfaces for every cell the netlist instantiates.

    Supply pins are left out, exactly as stage 2 left them out of the netlist:
    the sky130 models only expose them under USE_POWER_PINS and the reference
    netlist omits them too.
    """
    lines = ["// Generated by tools/stage3_graph.py from the PDK LEF.",
             "// Interfaces only: stage 3 reasons about connectivity, and the",
             "// behaviour of these cells is stage 2's simulation to check.",
             ""]
    for cell in sorted(cells):
        if cell not in lef:
            sys.exit(f"{cell} instantiated but absent from the LEF library")
        pins = functional_pins(lef[cell])
        lines.append("(* blackbox *)")
        lines.append(f"module {cell} ({', '.join(sorted(pins))});")
        for pin, direction in sorted(pins.items()):
            lines.append(f"  {direction} {pin};")
        lines.append("endmodule")
        lines.append("")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    return len(cells)


def run_yosys(netlist, blackbox, out_json, top):
    """Read the netlist under its blackbox library and dump Yosys's own JSON.

    `check` runs without `-assert`, and its findings are printed by the caller
    instead. An independent tool's opinion of the netlist is worth having in
    full; aborting on the first complaint would hide the rest of the list, and
    some of what it flags -- an output that drives nothing, for one -- is a real
    property of this design rather than a defect.
    """
    script = "; ".join([
        f"read_verilog -lib {blackbox}",
        f"read_verilog {netlist}",
        f"hierarchy -check -top {top}",
        "check",
        "stat",
        f"write_json {out_json}",
    ])
    result = subprocess.run(
        ["docker", "run", "--rm",
         "-v", f"{os.path.abspath('.')}:/work",
         "-w", "/work", IMAGE, "yosys", "-p", script],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(result.stdout[-4000:])
        print(result.stderr[-4000:])
        sys.exit("yosys failed")
    return result.stdout


def bit_key(bit):
    """Yosys writes a net as an integer and a constant as '0', '1', 'x', 'z'."""
    return f"const:{bit}" if isinstance(bit, str) else f"n{bit}"


def build_graph(design, top, lef, lib):
    module = design["modules"][top]
    cells = module["cells"]
    used = {c["type"] for c in cells.values()}

    # Pin directions come from the LEF, the same source stage 2 emitted the
    # netlist from, rather than from Yosys's view of a blackbox. One authority
    # for a fact, and the whole netlist already depends on this one. Liberty
    # states directions too, so the two are compared and any disagreement is
    # reported instead of one being picked.
    pins_of = {cell_type: functional_pins(lef[cell_type]) for cell_type in used}
    direction_clashes = []
    for cell_type in sorted(used):
        entry = lib.get(cell_type)
        if not entry:
            continue
        for pin, direction in sorted(pins_of[cell_type].items()):
            other = entry["pins"].get(pin, {}).get("direction")
            if other and other != direction:
                direction_clashes.append((cell_type, pin, direction, other))

    # --- nets and the pins on them ------------------------------------------
    net_pins = defaultdict(list)
    for instance, cell in cells.items():
        directions = pins_of[cell["type"]]
        for pin, bits in cell["connections"].items():
            for index, bit in enumerate(bits):
                net_pins[bit_key(bit)].append({
                    "instance": instance,
                    "cell": cell["type"],
                    "pin": pin if len(bits) == 1 else f"{pin}[{index}]",
                    "direction": directions.get(pin, "input"),
                })

    port_of = {}
    for name, port in module["ports"].items():
        for index, bit in enumerate(port["bits"]):
            port_of[bit_key(bit)] = {
                "port": name if len(port["bits"]) == 1 else f"{name}[{index}]",
                "direction": port["direction"],
            }

    names = {}
    for name, entry in module.get("netnames", {}).items():
        if entry.get("hide_name"):
            continue
        for index, bit in enumerate(entry["bits"]):
            names.setdefault(bit_key(bit),
                             name if len(entry["bits"]) == 1
                             else f"{name}[{index}]")

    # --- roles, as liberty states them --------------------------------------
    roles_of = {}
    for cell_type in sorted(used):
        entry = lib.get(cell_type)
        if not entry or not entry["sequential"]:
            continue
        state = entry["sequential"]
        clock, _ = liberty.pin_of(state["clocked_on"])
        data, _ = liberty.pin_of(state["next_state"])
        reset, reset_level = liberty.pin_of(state["clear"])
        preset, preset_level = liberty.pin_of(state["preset"])
        outputs = [p for p, d in pins_of[cell_type].items() if d == "output"]
        if clock is None or data is None or len(outputs) != 1:
            sys.exit(f"{cell_type} is sequential but its liberty entry does not "
                     f"reduce to one clock, one data pin and one output: "
                     f"{state}; add a rule rather than guessing")
        roles_of[cell_type] = {
            "kind": state["kind"], "clock": clock, "data": data,
            "q": outputs[0], "reset": reset, "reset_level": reset_level,
            "set": preset, "set_level": preset_level,
        }

    # Cross check against the naming convention. Not the authority -- six cells
    # in this library carry both RESET_B and SET_B and no name reading survives
    # that -- but a disagreement between the two is worth seeing.
    name_clashes = []
    for cell_type, roles in sorted(roles_of.items()):
        short = cell_type.split("__")[-1].split("_")[0]
        for kind in ("reset", "set"):
            present = roles[kind] is not None
            says = CELL_NAME_MARK[kind] in short[2:] or "bb" in short
            if present != says:
                name_clashes.append((cell_type, kind, present, says))

    clock_nets, reset_nets, set_nets = set(), set(), set()
    flipflops = {}
    for instance, cell in sorted(cells.items()):
        roles = roles_of.get(cell["type"])
        if roles is None:
            continue
        record = {"cell": cell["type"], "kind": roles["kind"]}
        for role in ("clock", "data", "q", "reset", "set"):
            pin = roles[role]
            bits = cell["connections"].get(pin) if pin else None
            record[role] = bit_key(bits[0]) if bits else None
        record["reset_level"] = roles["reset_level"]
        record["set_level"] = roles["set_level"]

        clock_nets.add(record["clock"])
        if record["reset"]:
            reset_nets.add(record["reset"])
        if record["set"]:
            set_nets.add(record["set"])
        flipflops[instance] = record

    # --- an enable implemented in logic rather than by a pin -----------------
    #
    # None of the sequential cells in this library carry an enable, so a held
    # register is built as a mux in front of D with the flop's own Q on one leg.
    # That is a structural fact, not an interpretation, so it belongs here.
    driver_of = {}
    for net, pins in net_pins.items():
        for pin in pins:
            if pin["direction"] == "output":
                driver_of[net] = pin

    for instance, record in flipflops.items():
        record["enable"] = None
        source = driver_of.get(record["data"])
        if source is None or "mux2" not in source["cell"]:
            continue
        mux = cells[source["instance"]]
        legs = {pin: bit_key(bits[0])
                for pin, bits in mux["connections"].items()
                if pin in ("A0", "A1") and len(bits) == 1}
        held = [pin for pin, net in legs.items() if net == record["q"]]
        if len(held) != 1:
            continue
        select = mux["connections"].get("S")
        record["enable"] = {
            "net": bit_key(select[0]) if select else None,
            "mux": source["instance"],
            "held_when": "high" if held[0] == "A1" else "low",
            "data_leg": legs["A0" if held[0] == "A1" else "A1"],
        }

    # --- constants -----------------------------------------------------------
    #
    # A constant is a cell output whose liberty function is the literal 1 or 0,
    # which is what `conb_1` is for. Read from the function rather than from the
    # cell's name, so a differently named constant generator is still caught.
    constant_nets = {}
    for net, pin in driver_of.items():
        entry = lib.get(pin["cell"])
        if not entry:
            continue
        function = (entry["pins"].get(pin["pin"], {}).get("function") or "").strip()
        if function in ("0", "1"):
            constant_nets[net] = int(function)
    for net in net_pins:
        if net.startswith("const:"):
            constant_nets[net] = net.split(":", 1)[1]

    # --- combinational cones -------------------------------------------------
    #
    # A cone root is somewhere combinational logic ends: a flip flop's data or
    # asynchronous input, or a primary output. Walking backwards from each root
    # until a flop output, a primary input or a constant stops it gives the nets
    # that root's value depends on this cycle.
    roots = {}
    for instance, record in flipflops.items():
        for role in ("data", "reset", "set"):
            if record[role]:
                roots[f"{instance}.{role}"] = record[role]
    for net, port in port_of.items():
        if port["direction"] == "output":
            roots[f"port.{port['port']}"] = net

    sequential_outputs = {record["q"] for record in flipflops.values()}
    boundary = sequential_outputs | set(constant_nets) | {
        net for net, port in port_of.items() if port["direction"] == "input"}

    cones = defaultdict(set)
    for name, start in sorted(roots.items()):
        seen = set()
        stack = [start]
        while stack:
            net = stack.pop()
            if net in seen:
                continue
            seen.add(net)
            cones[net].add(name)
            if net in boundary:
                continue
            source = driver_of.get(net)
            if source is None:
                continue
            cell = cells[source["instance"]]
            directions = pins_of[cell["type"]]
            for pin, bits in cell["connections"].items():
                if directions.get(pin) != "input":
                    continue
                for bit in bits:
                    stack.append(bit_key(bit))

    graph = {
        "target": None,
        "top": top,
        "cells": {instance: {"type": cell["type"],
                             "connections": {pin: [bit_key(b) for b in bits]
                                             for pin, bits in
                                             cell["connections"].items()}}
                  for instance, cell in sorted(cells.items())},
        "ports": {name: {"direction": port["direction"],
                         "bits": [bit_key(b) for b in port["bits"]]}
                  for name, port in sorted(module["ports"].items())},
        "net_names": names,
        "nets": {net: {"pins": pins,
                       "driver": driver_of.get(net, {}).get("instance"),
                       "cones": sorted(cones.get(net, ()))}
                 for net, pins in sorted(net_pins.items())},
        "clock_nets": sorted(clock_nets),
        "reset_nets": sorted(reset_nets),
        "set_nets": sorted(set_nets),
        "constant_nets": constant_nets,
        "flipflops": flipflops,
        "cone_roots": roots,
        # Kept for stages 4 and 6. Structural matching needs to know what a cell
        # computes, and a solver export is impossible without it: a netlist of
        # blackboxes can be walked as a graph and cannot be written to SMT2.
        "cell_functions": {
            cell_type: {pin: info["function"]
                        for pin, info in sorted(lib[cell_type]["pins"].items())
                        if info["function"]}
            for cell_type in sorted(used) if cell_type in lib},
        "cell_roles": roles_of,
        "source_disagreements": {
            "lef_vs_liberty_direction": direction_clashes,
            "liberty_vs_cell_name": name_clashes,
        },
    }
    return graph


def write_verilog(graph, path, lef):
    """The graph back out as Verilog, for the round trip gate.

    Written from the graph alone, never from stage 2's file, or the round trip
    would only prove that a copy is a copy.
    """
    buses, scalars = defaultdict(dict), {}
    for name, port in graph["ports"].items():
        if len(port["bits"]) == 1:
            scalars[name] = port
        else:
            for index, bit in enumerate(port["bits"]):
                buses[name][index] = bit
    port_direction = {name: port["direction"]
                      for name, port in graph["ports"].items()}

    of_net = {}
    for name, port in graph["ports"].items():
        for index, bit in enumerate(port["bits"]):
            of_net[bit] = name if len(port["bits"]) == 1 else f"{name}[{index}]"
    for net in graph["nets"]:
        of_net.setdefault(net, net if not net.startswith("const:")
                          else {"0": "1'b0", "1": "1'b1"}.get(
                              net.split(":", 1)[1], "1'bx"))

    lines = [f"module {graph['top']} ({', '.join(sorted(graph['ports']))});"]
    for name in sorted(scalars):
        lines.append(f"  {port_direction[name]} {name};")
    for name in sorted(buses):
        width = max(buses[name])
        lines.append(f"  {port_direction[name]} [{width}:0] {name};")
    lines.append("")

    port_nets = {bit for port in graph["ports"].values() for bit in port["bits"]}
    for net in sorted(graph["nets"]):
        if net in port_nets or net.startswith("const:"):
            continue
        lines.append(f"  wire {of_net[net]};")
    lines.append("")

    for instance, cell in sorted(graph["cells"].items()):
        allowed = functional_pins(lef[cell["type"]])
        wired = [f".{pin}({of_net[nets[0]]})"
                 for pin, nets in sorted(cell["connections"].items())
                 if pin in allowed and len(nets) == 1]
        if wired:
            lines.append(f"  {cell['type']} {instance} ({', '.join(wired)});")
    lines.append("endmodule")

    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    return sum(1 for line in lines if line.startswith("  sky130"))


def run(target):
    out_dir = os.path.join("out", target)
    netlist = os.path.join(out_dir, "netlist.v")
    if not os.path.exists(netlist):
        sys.exit(f"{netlist} missing, run tools/stage2_nets.py {target} first")

    with open(os.path.join(out_dir, "netlist.json"), encoding="utf-8") as handle:
        top = json.load(handle)["top"]

    text = open(netlist, encoding="utf-8").read()
    used = sorted(set(re.findall(r"^\s*(sky130_fd_sc_hd__\w+)\s", text, re.M)))
    lef = load_lef(PDK_DIR)
    lib = liberty.load(PDK_DIR)

    print(f"target {target}\ntop    {top}\ncells  {len(used)} types instantiated")
    without = [c for c in used if c not in lib]
    if without:
        sys.exit(f"no liberty entry for {without}; run tools/fetch_pdk.py")

    blackbox = os.path.join(out_dir, "blackbox.v")
    blackbox_library(used, lef, blackbox)
    print(f"wrote {blackbox}")

    yosys_json = os.path.join(out_dir, "yosys.json")
    log = run_yosys(netlist.replace("\\", "/"), blackbox.replace("\\", "/"),
                    yosys_json.replace("\\", "/"), top)
    for line in log.splitlines():
        if line.strip().startswith(("Number of cells", "Number of wires",
                                    "Number of public wires")):
            print(f"  yosys: {line.strip()}")

    complaints = [line.strip() for line in log.splitlines()
                  if line.startswith(("Warning:", "Found and reported"))
                  or "problems." in line]
    if complaints:
        print("  yosys check:")
        for line in complaints[:20]:
            print(f"    {line}")
        if len(complaints) > 20:
            print(f"    ... and {len(complaints) - 20} more")

    with open(yosys_json, encoding="utf-8") as handle:
        design = json.load(handle)
    if top not in design["modules"]:
        sys.exit(f"yosys produced no module named {top!r}")

    graph = build_graph(design, top, lef, lib)
    graph["target"] = target

    clashes = graph["source_disagreements"]
    for label, entries in sorted(clashes.items()):
        if entries:
            print(f"\nSOURCES DISAGREE, {label}: {len(entries)}")
            for entry in entries[:10]:
                print(f"  {entry}")
        else:
            print(f"  sources agree: {label}")

    print(f"\ncells {len(graph['cells'])}, nets {len(graph['nets'])}, "
          f"ports {len(graph['ports'])}")
    print(f"clock nets {len(graph['clock_nets'])}: "
          f"{[graph['net_names'].get(n, n) for n in graph['clock_nets']]}")
    print(f"reset nets {len(graph['reset_nets'])}, "
          f"set nets {len(graph['set_nets'])}, "
          f"constant nets {len(graph['constant_nets'])}")
    print(f"state elements {len(graph['flipflops'])}: "
          f"{dict(Counter(r['cell'].split('__')[-1] for r in graph['flipflops'].values()))}")
    for cell_type, roles in sorted(graph["cell_roles"].items()):
        print(f"  {cell_type.split('__')[-1]:<12} {roles['kind']:<5} "
              f"clock={roles['clock']} data={roles['data']} q={roles['q']} "
              f"reset={roles['reset']}({roles['reset_level']}) "
              f"set={roles['set']}({roles['set_level']})")
    print(f"cell functions kept for stages 4 and 6: "
          f"{len(graph['cell_functions'])} cell types")
    enabled = [i for i, r in graph["flipflops"].items() if r["enable"]]
    print(f"  with an enable built from a mux in front of D: {len(enabled)}")
    if enabled:
        nets = Counter(graph["net_names"].get(graph["flipflops"][i]["enable"]["net"],
                                              graph["flipflops"][i]["enable"]["net"])
                       for i in enabled)
        print(f"  enable nets: {dict(nets)}")
    print(f"cone roots {len(graph['cone_roots'])}")
    sizes = Counter(len(entry["cones"]) for entry in graph["nets"].values())
    print(f"  nets in no cone: {sizes.get(0, 0)}, in exactly one: {sizes.get(1, 0)}, "
          f"in more: {sum(c for n, c in sizes.items() if n > 1)}")

    graph_path = os.path.join(out_dir, "graph.json")
    with open(graph_path, "w", encoding="utf-8") as handle:
        json.dump(graph, handle, indent=1)
    print(f"\nwrote {graph_path}")

    verilog_path = os.path.join(out_dir, "graph.v")
    emitted = write_verilog(graph, verilog_path, lef)
    print(f"wrote {verilog_path} with {emitted} instances")
    print(f"\nround trip gate: python tools/sim/run.py {target} "
          f"--netlist {verilog_path}")
    return 0


if __name__ == "__main__":
    args = sys.argv[1:]
    if len(args) != 1 or args[0] not in TARGETS:
        sys.exit(f"usage: python tools/stage3_graph.py [{' | '.join(TARGETS)}]")
    sys.exit(run(args[0]))
